'use strict';
const $=id=>document.getElementById(id), finite=Number.isFinite;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(v,d=2)=>finite(v)?v.toFixed(d):'—';
const palette=['#64dfc8','#b39aff','#edbd70','#68bfff','#f497b5','#9ecd72','#c49dd8','#8bd4e5','#e69f71','#bacb83','#938ee0','#c6bd84','#87bfa5','#d18ab5','#859ecb'];
let metadata={},snapshot={},evidence={},history=[],layout=[],ws,activeTab='timeline',recorded=false,recordedFrames=[],recordIndex=0,recordTimer=null,atlasPoints=[],gl=null,glProgram=null,lastFrame=-1,metadataReady=false,renderPending=false,heatmapMode='after',rasterData=null,weightData=null,atlasColorBuffer=null,atlasBounds=null,selection=null,playhead=null,dragStart=null;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function toast(message,error=false){$('toast').textContent=message;$('toast').style.borderColor=error?'#be8173':'#537981';$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,5000)}
async function control(control_id,value){if(recorded){toast('Recorded playback is read-only. Reload to return to the live engine.');return}try{const r=await fetch('/api/control',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({control_id,value})});const j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Control failed');return j.result}catch(e){toast(e.message,true)}}
function bindRange(id,key,out){$(id).addEventListener('input',()=>$(out).textContent=Number($(id).value).toFixed(2));$(id).addEventListener('change',()=>control(key,Number($(id).value)))}
bindRange('intensity','intensity','intensity-value');bindRange('dan-drive','dan_drive','dan-value');bindRange('oa-tone','oa_tone','oa-value');bindRange('serotonin-tone','serotonin_tone','serotonin-value');bindRange('energy','state.energy','energy-value');bindRange('hydration','state.hydration','hydration-value');
for(const b of document.querySelectorAll('[data-odour]'))b.onclick=()=>control('odour',b.dataset.odour);
$('dan-type').onchange=()=>{sourceWarning($('dan-type').value);control('dan_type',$('dan-type').value)};
$('pulse').onclick=()=>control('dan.pulse',{drive:1,duration_ms:500});
$('fed').onclick=()=>control('nutritional_state','fed');$('starved').onclick=()=>control('nutritional_state','starved');
$('field-concentration').oninput=()=>$('field-value').textContent=Number($('field-concentration').value).toFixed(2);
$('clamp-field').onclick=()=>control('field.clamp',{species:$('field-species').value,compartment:$('field-compartment').value,value:Number($('field-concentration').value)});
$('release-field').onclick=()=>control('field.clamp',null);
$('play').onclick=()=>{if(recorded){if(recordTimer){clearInterval(recordTimer);recordTimer=null;$('play').textContent='▶ Play';$('play').setAttribute('aria-label','Play recording')}else{recordTimer=setInterval(()=>{if(recordIndex>=recordedFrames.length-1){clearInterval(recordTimer);recordTimer=null;updateStatus({paused:true});return}showRecorded(++recordIndex)},reduced?200:33);$('play').textContent='Ⅱ Pause';$('play').setAttribute('aria-label','Pause recording')}}else control('pause',!snapshot.paused)};
$('step').onclick=()=>recorded?showRecorded(Math.min(recordIndex+1,recordedFrames.length-1)):control('step',1);
$('reset').onclick=()=>{if(recorded){history=[];showRecorded(0)}else{history=[];control('reset',snapshot.seed??7)}};
$('export').onclick=()=>{if(recorded){toast('This is a loaded recording. Its original archive contains the complete session.');return}location.href='/api/session'};
for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>{activeTab=b.dataset.tab;document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===activeTab));requestRender()};
$('window').onchange=requestRender;
$('timeline-species').onchange=requestRender;
for(const b of document.querySelectorAll('[data-heatmap]'))b.onclick=()=>{heatmapMode=b.dataset.heatmap;document.querySelectorAll('[data-heatmap]').forEach(x=>x.classList.toggle('active',x===b));$('heatmap-label').textContent=heatmapMode==='before'?'Initial baseline = 1':heatmapMode==='difference'?'Current / baseline − 1':'Current weight / baseline';requestRender()};
$('raster-fetch').onclick=async()=>{if(recorded)return toast('Sampled recording playback does not load the binary spike stream; use the exported raw logs for individual spikes.');try{const query=new URLSearchParams({cell_type:$('raster-subtype').value,duration_ms:$('raster-window').value,max_points:'20000'});const r=await fetch('/api/raster?'+query);const received=await r.json();if(recorded)return;rasterData=received;if(!r.ok)throw Error(rasterData.error);$('raster-note').textContent=`${rasterData.retained_spikes.toLocaleString()} actual spikes shown / ${rasterData.matching_spikes.toLocaleString()} matching events; ${rasterData.omitted_spikes.toLocaleString()} omitted by cap. ${rasterData.neuron_indices.length} neurons, ${fmt(rasterData.window_start_ms/1000,3)}–${fmt(rasterData.window_end_ms/1000,3)} s. Most recent events retained; no interpolation.`;drawRaster()}catch(e){toast(e.message,true)}};
function drawRaster(){const [ctx,w,h]=canvas2d('raster-canvas');if(!rasterData)return;const d=rasterData,rows=new Map(d.neuron_indices.map((v,i)=>[v,i])),left=45,top=12,rh=(h-35)/Math.max(1,rows.size),span=d.window_end_ms-d.window_start_ms;ctx.fillStyle='#6eddc4';for(let i=0;i<d.spike_indices.length;i++){const row=rows.get(d.spike_indices[i]);if(row===undefined)continue;const x=left+(d.spike_times_ms[i]-d.window_start_ms)/span*(w-left-12),y=top+row*rh;ctx.fillRect(x,y,1,Math.max(1,rh*.7))}ctx.fillStyle='#91a5b9';ctx.font='9px ui-monospace';ctx.fillText('KC 0',4,15);ctx.fillText(String(rows.size-1),4,h-30);ctx.fillText(fmt(d.window_start_ms/1000,2)+'s',left,h-9);ctx.fillText(fmt(d.window_end_ms/1000,2)+'s',w-53,h-9)}
function sourceWarning(type){const a=metadata.atlas;if(!a||!type)return;const compartments=new Set();a.cell_types.forEach((ct,i)=>{if(ct===type&&a.compartment[i]>=0)compartments.add(metadata.compartments[a.compartment[i]])});const actual=[...compartments].join(', ')||'no assigned MB compartment';$('compartment-warning').textContent=`${type}: empirical ${actual}. ${type==='PPL101'?'Published anatomy: g1. This measured disagreement is retained.':'Source identity is preserved; no canonical remapping.'}`}

document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName))return;if(e.code==='Space'){e.preventDefault();$('play').click()}if(e.key===']')$('step').click();if(e.key==='p')$('pulse').click();if(e.key==='1')control('odour','air');if(e.key==='2')control('odour','OCT');if(e.key==='3')control('odour','MCH')});
function protocolPreset(){const delay=Number($('pairing').value);$('pairing-value').textContent=(delay>=0?'+':'')+delay+' ms';$('protocol-yaml').value=`name: ${delay>=0?'forward':'backward'}_pairing\nseed: ${snapshot.seed??7}\nblocks:\n  - {t_ms: 0, kind: rest, dur_ms: 3000}\n  - {t_ms: 3000, kind: odour, id: OCT, dur_ms: 1000, intensity: 1.0}\n  - {t_ms: ${3000+delay}, kind: dan_pulse, source: PPL101, compartment: g1, dur_ms: 500, drive: 1.0}\n  - {t_ms: 6500, kind: test, odours: [OCT, MCH], dur_ms: 1000, iti_ms: 1000}\n`;$('protocol-track').querySelector('.dan-block').style.left=(3000+delay)/7000*100+'%'}
$('pairing').oninput=protocolPreset;$('forward-preset').onclick=()=>{$('pairing').value=500;protocolPreset()};$('backward-preset').onclick=()=>{$('pairing').value=-1500;protocolPreset()};protocolPreset();
$('run-protocol').onclick=async()=>{if(recorded)return toast('Recorded playback is read-only.');try{const r=await fetch('/api/protocol',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({yaml:$('protocol-yaml').value})});const j=await r.json();if(!r.ok)throw Error(j.error);history=[];toast('Protocol armed on the simulation clock.')}catch(e){toast(e.message,true)}};
function applyMetadata(m){if(!m||!m.neurons)return;metadata=m;metadataReady=true;$('timeline-species').innerHTML=(m.species||[]).map(x=>`<option>${esc(x)}</option>`).join('');$('raster-subtype').innerHTML='<option value="all">All Kenyon cells</option>'+(m.kc_types||[]).map(x=>`<option>${esc(x)}</option>`).join('');$('core-count').textContent=m.neurons.toLocaleString();$('dan-type').innerHTML=(m.dan_types||[]).map(t=>`<option value="${esc(t)}">${esc(t)}</option>`).join('');if(m.dan_types?.includes('PPL101'))$('dan-type').value='PPL101';$('field-species').innerHTML=(m.species||[]).map(x=>`<option>${esc(x)}</option>`).join('');$('field-compartment').innerHTML=(m.compartments||[]).map(x=>`<option>${esc(x)}</option>`).join('');$('field-compartment').value='g4';$('mbon-meters').innerHTML=(m.mbon_types||[]).map((t,i)=>`<div class="meter"><span>${esc(t)}</span><div class="meter-track"><div class="meter-fill" id="meter-${i}"></div></div><span class="meter-number" id="rate-${i}">—</span></div>`).join('');$('limitations').innerHTML=(m.warnings||[]).map(x=>`<p>↳ ${esc(x)}</p>`).join('');$('atlas-species').innerHTML=(m.species||[]).map(x=>`<option>${esc(x)}</option>`).join('');$('weight-compartment').innerHTML='<option value="all">All MB compartments</option>'+(m.compartments||[]).slice(0,15).map(x=>`<option>${esc(x)}</option>`).join('');$('weight-subtype').innerHTML='<option value="all">All KC types</option>'+(m.kc_types||[]).map(x=>`<option>${esc(x)}</option>`).join('');setupAtlas();sourceWarning(snapshot.controls?.dan_type||'PPL101');requestRender()}
function updateStatus(s){snapshot={...snapshot,...s};const t=snapshot.t_sim_ms;$('clock').textContent=finite(t)?(t/1000).toFixed(3)+' s':'—';$('speed').textContent=fmt(snapshot.rtf,2)+' ×';$('speed').classList.toggle('bad',finite(snapshot.rtf)&&snapshot.rtf<1);$('memory').textContent=fmt(snapshot.rss_gb,2)+' GB';$('seed').textContent=snapshot.seed??'—';$('config').textContent=(snapshot.config_hash||'').slice(0,9)||'—';$('play').textContent=snapshot.paused?(recorded?'▶ Play':'▶ Resume'):'Ⅱ Pause';$('play').setAttribute('aria-label',recorded?(snapshot.paused?'Play recording':'Pause recording'):(snapshot.paused?'Resume simulation':'Pause simulation'));$('step').textContent=recorded?'Next frame':'Step +1 ms';$('step').title=recorded?'Advance one saved frame at its original timestamp':'Advance 1 simulation millisecond';$('recording').textContent=recorded?'○ RECORDED PLAYBACK':snapshot.recording?'● RECORDING':'○ not recording';$('valence').textContent=fmt(snapshot.valence,3);$('valence-marker').style.visibility=finite(snapshot.valence)?'visible':'hidden';if(finite(snapshot.valence)){$('valence-marker').style.visibility='visible';$('valence-marker').style.left=(50+Math.max(-48,Math.min(48,snapshot.valence*4)))+'%'}$('kc-fraction').textContent=finite(snapshot.kc_active_fraction)?(snapshot.kc_active_fraction*100).toFixed(1)+'%':'—';$('voltage').textContent=fmt(snapshot.voltage_min_mV,1)+' / '+fmt(snapshot.voltage_max_mV,1)+' mV';const violations=finite(snapshot.voltage_out_of_bounds)?snapshot.voltage_out_of_bounds:null;$('voltage-warning').textContent=violations===null?'Voltage-bound diagnostic unavailable in this sample.':violations?`${violations.toLocaleString()} samples outside −90 / +20 mV. Unclamped.`:'Unclamped trajectory; limits −90 to +20 mV.';$('voltage-warning').classList.toggle('bad',!!violations);$('weight-change').textContent=fmt(snapshot.total_absolute_weight_change,4);
 const c=snapshot.controls||{};document.querySelectorAll('[data-odour]').forEach(b=>b.classList.toggle('active',b.dataset.odour===c.odour));for(const [key,id,out] of [['intensity','intensity','intensity-value'],['dan_drive','dan-drive','dan-value'],['oa_tone','oa-tone','oa-value'],['serotonin_tone','serotonin-tone','serotonin-value']])if(finite(c[key])&&document.activeElement!==$(id)){$(id).value=c[key];$(out).textContent=c[key].toFixed(2)}if(c.dan_type&&document.activeElement!==$('dan-type'))$('dan-type').value=c.dan_type;sourceWarning(c.dan_type);for(const key of ['energy','hydration'])if(finite(snapshot.state?.[key])&&document.activeElement!==$(key)){$(key).value=snapshot.state[key];$(key+'-value').textContent=snapshot.state[key].toFixed(2)}
 (snapshot.mbon_rates_hz||[]).forEach((v,i)=>{if($('meter-'+i)){$('meter-'+i).style.width=Math.min(100,v)+'%';$('rate-'+i).textContent=fmt(v,1)}});$('integrity').innerHTML=[['Voltage clamps',snapshot.voltage_clamps],['Outside voltage bounds',snapshot.voltage_out_of_bounds],['Field clamps',snapshot.field_clamps],['Weight clamps',snapshot.weight_clamps],['KC rate saturation',snapshot.kc_rate_saturations]].map(([k,v])=>`<div><dt>${k}</dt><dd class="${v?'bad':''}">${v?.toLocaleString()??'—'}</dd></div>`).join('');const events=snapshot.recent_events||[];$('event-count').textContent=events.length;$('events').innerHTML=events.length?events.slice().reverse().map(e=>`<div class="event"><time>${fmt(e.t_sim_ms/1000,3)} s</time>${esc(e.control_id)} → ${esc(typeof e.value==='object'?JSON.stringify(e.value):e.value)}</div>`).join(''):'<p>No controls recorded yet.</p>';
 const notices=[];if(snapshot.error)notices.push(snapshot.error);if(recorded)notices.push('Recorded session · no engine controls · original simulation timestamps');else if(snapshot.status==='starting')notices.push(snapshot.message||'Loading verified core');else if(snapshot.paused)notices.push('Paused on the simulation clock');else if(snapshot.rtf<1)notices.push('Slower than real time · model time is never replaced by wall time');if(violations)notices.push('Measured voltage bounds failure remains visible');if(!notices.length)notices.push('Live 13,300-neuron core · actual connectome · normalized plasticity · every control recorded');$('notice').textContent=notices.join('  /  ');$('notice').classList.toggle('warning',!!snapshot.error||!!violations);requestRender()}
function addSample(s){if(history.length&&s.t_sim_ms<history.at(-1).t_sim_ms){history=[];selection=null;playhead=null;}if(!history.length||s.t_sim_ms!==history.at(-1).t_sim_ms)history.push(structuredClone(s));if(history.length>5000)history.splice(0,history.length-5000);$('empty-timeline').style.display=history.length?'none':'grid'}
function binarySample(buffer){const a=new Float32Array(buffer);if(a[0]!==1||a.length!==a[5]+6)return toast('Unsupported or incomplete binary frame',true);if(lastFrame>=0&&a[4]!==lastFrame+1)snapshot.transport_gap=true;lastFrame=a[4];const next={...snapshot,t_sim_ms:a[1],dt_ms:a[2],rtf:a[3]};for(const field of layout){let values=Array.from(a.slice(6+field.offset,6+field.offset+field.length),v=>finite(v)?v:null);if(field.length===1&&['valence','kc_active_fraction','voltage_min_mV','voltage_max_mV','voltage_out_of_bounds','spikes','total_absolute_weight_change'].includes(field.name))next[field.name]=values[0];else if(field.name==='concentrations_au'){const n=metadata.compartments?.length||0;next[field.name]=n?Array.from({length:values.length/n},(_,i)=>values.slice(i*n,(i+1)*n)):[]}else if(field.name==='weight_heatmap'){const n=metadata.kc_types?.length||0;next[field.name]=n?Array.from({length:15},(_,i)=>values.slice(i*n,(i+1)*n)):[]}else next[field.name]=values}updateStatus(next);addSample(next)}
function connect(){if(recorded)return;ws=new WebSocket(`${location.protocol==='https:'?'wss:':'ws:'}//${location.host}/ws`);ws.binaryType='arraybuffer';ws.onopen=()=>{$('connection').textContent='● LIVE LINK';$('connection').classList.add('live')};ws.onmessage=e=>{if(recorded)return;if(e.data instanceof ArrayBuffer)binarySample(e.data);else{const data=JSON.parse(e.data);if(data.kind==='schema')layout=data.layout;if(data.kind==='status')updateStatus(data.snapshot)}};ws.onclose=()=>{if(recorded)return;$('connection').textContent='○ DISCONNECTED';$('connection').classList.remove('live');$('notice').textContent='Engine connection lost. Last measured sample retained; new data is a gap.';setTimeout(connect,3000)};ws.onerror=()=>ws.close()}
function size(canvas){const r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;if(canvas.width!==Math.round(r.width*d)||canvas.height!==Math.round(r.height*d)){canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d)}return [r.width,r.height,d]}
function canvas2d(id){const c=$(id),[w,h,d]=size(c),ctx=c.getContext('2d');ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);return [ctx,w,h]}
function requestRender(){if(renderPending)return;renderPending=true;requestAnimationFrame(()=>{renderPending=false;if(activeTab==='timeline'){drawTimeline();if(rasterData)drawRaster();}if(activeTab==='atlas')drawAtlas();if(activeTab==='learning'){drawHeatmap();drawLearningHistory()}})}
function drawTimeline({context=null,width=null,height=null,bounds=null}={}){const [ctx,w,h]=context?[context,width,height]:canvas2d('timeline-canvas');const margin=100,right=16,top=25,bottom=28,lanes=10,lh=(h-top-bottom)/lanes;const duration=Number($('window').value),end=bounds?bounds[1]:(history.at(-1)?.t_sim_ms||duration),start=bounds?bounds[0]:Math.max(0,end-duration),span=bounds?Math.max(1,end-start):Math.max(duration,end-start),data=history.filter(s=>s.t_sim_ms>=start&&s.t_sim_ms<=end),x=t=>margin+(t-start)/span*(w-margin-right);const labels=['STIMULUS','KC SUBTYPES','DAN · Hz',($('timeline-species').value||'DA')+' · a.u.','WEIGHTS / w₀','MBON VALENCE','INTERNAL STATE','MBON TYPES · Hz','BODY READOUT','CONTROLS'];ctx.font='8px -apple-system';ctx.fillStyle='#8297ab';for(let j=0;j<lanes;j++){const y=top+j*lh;ctx.fillText(labels[j],12,y+16);ctx.strokeStyle='#233043';ctx.beginPath();ctx.moveTo(margin,y+lh);ctx.lineTo(w-right,y+lh);ctx.stroke()}for(let j=0;j<=5;j++){const t=start+span*j/5;ctx.fillStyle='#61778d';ctx.fillText((t/1000).toFixed(1)+'s',x(t)-9,h-9);ctx.strokeStyle='#1a2736';ctx.beginPath();ctx.moveTo(x(t),top);ctx.lineTo(x(t),h-bottom);ctx.stroke()}if(!data.length)return;
 const ci=Math.max(0,metadata.compartments?.indexOf($('field-compartment').value)??3),si=Math.max(0,metadata.species?.indexOf($('timeline-species').value)??0);let maxDan=Math.max(1,...data.flatMap(s=>s.dan_rates_hz||[]).filter(finite)),maxVal=Math.max(1,...data.map(s=>Math.abs(s.valence||0))),maxC=Math.max(1,...data.map(s=>s.concentrations_au?.[si]?.[ci]||0));
 for(const s of data){const px=x(s.t_sim_ms);if(s.controls?.odour&&s.controls.odour!=='air'){ctx.fillStyle=s.controls.odour==='OCT'?'#64dfc8':'#b39aff';ctx.fillRect(px,top+12,2,lh-23)}(s.kc_rates_hz||[]).forEach((v,i)=>{ctx.fillStyle=`rgba(100,223,200,${Math.min(1,v/100)})`;ctx.fillRect(px,top+lh+8+i*(lh-14)/11,2,(lh-14)/11)});(s.dan_rates_hz||[]).forEach((v,i)=>{if(!finite(v))return;ctx.fillStyle=palette[i%15];ctx.fillRect(px,top+3*lh-7-v/maxDan*(lh-15),1.4,1.6)});const c=s.concentrations_au?.[si]?.[ci];if(finite(c)){ctx.fillStyle='#edbd70';if(Math.floor(px)%5<3)ctx.fillRect(px,top+4*lh-7-c/maxC*(lh-15),2,2)}(s.weights_relative||[]).forEach((v,i)=>{if(!finite(v))return;ctx.fillStyle=palette[i%15];if(Math.floor(px)%5<3)ctx.fillRect(px,top+4.5*lh-(v-1)*(lh*.9),1.6,1.6)});if(finite(s.valence)){ctx.fillStyle='#b39aff';ctx.fillRect(px,top+5.5*lh-s.valence/maxVal*(lh*.38),1.6,2)}}
 for(const s of data){for(const [key,color,j] of [['energy','#64dfc8',0],['hydration','#68bfff',1]]){const v=s.state?.[key];if(finite(v)){ctx.fillStyle=color;if(Math.floor(x(s.t_sim_ms))%5<3)ctx.fillRect(x(s.t_sim_ms),top+7*lh-7-v*(lh-15),1.6,1.6)}}}for(const s of data)(s.mbon_rates_hz||[]).forEach((v,i)=>{if(!finite(v))return;ctx.fillStyle=`rgba(179,154,255,${Math.min(1,v/100)})`;ctx.fillRect(x(s.t_sim_ms),top+7*lh+6+i*(lh-12)/(metadata.mbon_types?.length||35),2,Math.max(1,(lh-12)/(metadata.mbon_types?.length||35)))});ctx.fillStyle='#101924';ctx.fillRect(margin,top+8*lh+3,w-margin-right,lh-6);ctx.strokeStyle='#293747';for(let xx=margin;xx<w-right;xx+=12){ctx.beginPath();ctx.moveTo(xx,top+9*lh-5);ctx.lineTo(Math.min(xx+20,w-right),top+8*lh+5);ctx.stroke()}ctx.fillStyle='#7e92a7';ctx.font='9px -apple-system';ctx.fillText('NOT-RUN · no validated motor decoder',margin+12,top+8.55*lh);const last=data.at(-1);for(const e of last.recent_events||[]){if(e.t_sim_ms<start||e.t_sim_ms>end)continue;ctx.fillStyle='#64dfc8';ctx.fillRect(x(e.t_sim_ms),top+9*lh+10,1,lh-18)}ctx.fillStyle='#bdd0db';ctx.font='9px ui-monospace';ctx.fillText('0–'+maxDan.toFixed(0),w-54,top+2*lh+12);ctx.fillText(($('field-compartment').value||'g4')+'  '+maxC.toFixed(1),w-66,top+3*lh+12);if(selection&&!bounds){ctx.fillStyle='#68bfff18';ctx.fillRect(x(selection[0]),top,x(selection[1])-x(selection[0]),h-top-bottom)}if(finite(playhead)&&!bounds){ctx.strokeStyle='#d9e6ef';ctx.setLineDash([3,3]);ctx.beginPath();ctx.moveTo(x(playhead),top);ctx.lineTo(x(playhead),h-bottom);ctx.stroke();ctx.setLineDash([])}}
function drawHeatmap(){const [ctx,w,h]=canvas2d('heatmap-canvas'),heat=snapshot.weight_heatmap||[],types=metadata.kc_types||[],names=(metadata.compartments||[]).slice(0,15);ctx.font='8px -apple-system';const left=52,top=47,cw=(w-left-15)/Math.max(1,types.length),rh=(h-top-12)/15;types.forEach((v,i)=>{ctx.fillStyle='#8ca2b6';ctx.save();ctx.translate(left+i*cw+cw*.3,top-9);ctx.rotate(-.45);ctx.fillText(v,0,0);ctx.restore()});names.forEach((name,j)=>{ctx.fillStyle='#9caebe';ctx.fillText(name,12,top+j*rh+rh*.65);types.forEach((_,i)=>{const raw=heat[j]?.[i],v=finite(raw)?(heatmapMode==='before'?1:heatmapMode==='difference'?raw-1:raw):null,x=left+i*cw,y=top+j*rh;if(!finite(v)){ctx.fillStyle='#111923';ctx.fillRect(x+1,y+1,cw-2,rh-2);ctx.strokeStyle='#263242';ctx.beginPath();ctx.moveTo(x+3,y+rh-3);ctx.lineTo(x+cw-3,y+3);ctx.stroke()}else{const delta=heatmapMode==='difference'?v:v-1,a=Math.min(1,Math.abs(delta)/.15);ctx.fillStyle=delta<0?`rgb(${25+25*a},${43+80*a},${57+100*a})`:`rgb(${35+140*a},${45+90*a},${50+30*a})`;ctx.fillRect(x+1,y+1,cw-2,rh-2);if(cw>40){ctx.fillStyle='#bed0dc';ctx.fillText(v.toFixed(3),x+cw*.2,y+rh*.7)}}})})}
function setupAtlas(){const atlas=metadata.atlas;if(!atlas?.xyz)return;const valid=atlas.xyz.map((p,i)=>p?{p,i}:null).filter(Boolean);if(!valid.length)return;const xs=valid.map(x=>x.p[0]),ys=valid.map(x=>x.p[1]);atlasBounds={xmin:Math.min(...xs),xmax:Math.max(...xs),ymin:Math.min(...ys),ymax:Math.max(...ys)};const {xmin,xmax,ymin,ymax}=atlasBounds;atlasPoints=valid.map(({p,i})=>({x:(p[0]-xmin)/(xmax-xmin)*1.8-.9,y:((p[1]-ymin)/(ymax-ymin)*1.8-.9)*-1,i}));const canvas=$('atlas-canvas');gl=canvas.getContext('webgl',{antialias:true,alpha:false});if(!gl)return;const shader=(type,code)=>{const sh=gl.createShader(type);gl.shaderSource(sh,code);gl.compileShader(sh);if(!gl.getShaderParameter(sh,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(sh));return sh};glProgram=gl.createProgram();gl.attachShader(glProgram,shader(gl.VERTEX_SHADER,'attribute vec2 position;attribute vec3 color;varying vec3 c;void main(){gl_Position=vec4(position,0.,1.);gl_PointSize=2.;c=color;}'));gl.attachShader(glProgram,shader(gl.FRAGMENT_SHADER,'precision mediump float;varying vec3 c;void main(){gl_FragColor=vec4(c,1.);}'));gl.linkProgram(glProgram);gl.useProgram(glProgram);const positions=new Float32Array(atlasPoints.flatMap(p=>[p.x,p.y]));for(const [name,data,n] of [['position',positions,2],['color',new Float32Array(atlasPoints.length*3),3]]){const b=gl.createBuffer();if(name==='color')atlasColorBuffer=b;gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,data,gl.DYNAMIC_DRAW);const loc=gl.getAttribLocation(glProgram,name);gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,n,gl.FLOAT,false,0,0)}}
function atlasColors(){const mode=$('atlas-mode').value,a=metadata.atlas||{},samples=new Map((a.sample_indices||[]).map((v,i)=>[v,i]));return atlasPoints.map(p=>{if(mode==='compartment'){const hex=palette[a.compartment?.[p.i]]||'#334655';return [1,3,5].map(o=>parseInt(hex.slice(o,o+2),16)/255)}const j=samples.get(p.i),value=(mode==='rate'?snapshot.atlas_rates_hz:snapshot.atlas_voltage_mV)?.[j];if(!finite(value))return [.12,.17,.22];const v=mode==='rate'?Math.min(1,value/100):Math.max(0,Math.min(1,(value+90)/110));return mode==='rate'?[.12+.28*v,.24+.64*v,.3+.45*v]:[.15+.8*v,.35+.23*(1-v),.8-.65*v]})}
function drawAtlas(){const canvas=$('atlas-canvas'),[w,h,d]=size(canvas),colors=atlasColors();if(gl){gl.viewport(0,0,w*d,h*d);gl.bindBuffer(gl.ARRAY_BUFFER,atlasColorBuffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(colors.flat()),gl.DYNAMIC_DRAW);gl.clearColor(.03,.047,.074,1);gl.clear(gl.COLOR_BUFFER_BIT);gl.drawArrays(gl.POINTS,0,atlasPoints.length)}else{const ctx=canvas.getContext('2d');if(!ctx)return;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);atlasPoints.forEach((p,i)=>{ctx.fillStyle=`rgb(${colors[i].map(v=>Math.round(v*255)).join(',')})`;ctx.fillRect((p.x+1)/2*w,(1-p.y)/2*h,1.4,1.4)})}const [ctx,ow,oh]=canvas2d('atlas-overlay'),species=$('atlas-species').value,si=metadata.species?.indexOf(species);if($('atlas-hulls').checked&&atlasBounds){const b=atlasBounds;for(const hull of metadata.atlas?.schematic_hulls||[]){const ci=metadata.compartments.indexOf(hull.compartment),v=snapshot.concentrations_au?.[si]?.[ci];if(!finite(v)||v<=0)continue;ctx.strokeStyle=`rgba(237,189,112,${.15+.6*Math.min(v,1)})`;ctx.fillStyle=`rgba(237,189,112,${.002+.006*Math.min(v,1)})`;ctx.beginPath();hull.xy.forEach(([x,y],j)=>{const px=((x-b.xmin)/(b.xmax-b.xmin)*.9+.05)*ow,py=((y-b.ymin)/(b.ymax-b.ymin)*.9+.05)*oh;j?ctx.lineTo(px,py):ctx.moveTo(px,py)});ctx.closePath();ctx.fill();ctx.stroke()}}const mode=$('atlas-mode').value,available=(mode==='voltage'?snapshot.atlas_voltage_mV:snapshot.atlas_rates_hz)?.filter(finite).length||0;$('atlas-note').textContent=`${atlasPoints.length.toLocaleString()} released positions. ${mode==='compartment'?'Colour: empirical membership.':`${available} measured activity samples; unsampled neurons are unknown. Scale ${mode==='rate'?'0–100 Hz (saturates colour only)':'−90 to +20 mV'}.`} ${species} overlay: assumed concentration on schematic assigned-soma extents; not anatomical field geometry.`}
$('atlas-canvas').onmousemove=e=>{const rect=e.target.getBoundingClientRect(),mx=e.clientX-rect.left,my=e.clientY-rect.top;let nearest=null,best=64;for(const p of atlasPoints){const x=(p.x+1)/2*rect.width,y=(1-p.y)/2*rect.height,dist=(x-mx)**2+(y-my)**2;if(dist<best){best=dist;nearest=p}}const tip=$('atlas-tip');if(!nearest){tip.hidden=true;return}const i=nearest.i,a=metadata.atlas,known=a.known_nt[i],pred=a.predicted_nt[i],positive=known.split(/[;,]/).map(x=>x.trim().toLowerCase()).filter(x=>!x.endsWith('-negative')&&['acetylcholine','dopamine','gaba','glutamate','octopamine','serotonin','tyramine','histamine'].includes(x)),disagrees=positive.length&&pred&&!positive.includes(pred.toLowerCase());tip.innerHTML=`<b>${esc(a.cell_types[i]||'Untyped neuron')}</b><br><code>${esc(a.root_ids[i])}</code><br>${atlasActivity(i)}<br>Ground truth: ${esc(known||'not annotated')}<br>Prediction: ${esc(pred||'not annotated')}${disagrees?'<br><span class="warning">Predictor disagrees with ground truth</span>':''}`;tip.style.left=Math.min(mx+12,rect.width-292)+'px';tip.style.top=Math.min(my+12,rect.height-140)+'px';tip.hidden=false};$('atlas-canvas').onmouseleave=()=>$('atlas-tip').hidden=true;
function showEvidence(e){evidence=e||{};const gates=evidence.gates||[],by=new Map(gates.map(g=>[g.gate,g]));const requested=['V-NM-C','V-NM-COMP','V-NM-D','V-NM-ODOUR','V-NM-CORE','V-NM-A','V-NM-E','V-NM-F','V-NM-G','V-NM-H','V-NM-I','V-NM-J','V-NM-ODSP','V-NM-B',"V-NM-F'"];$('fail-count').textContent=gates.filter(g=>g.status==='FAIL').length||'';$('gate-table').querySelector('tbody').innerHTML=requested.map(id=>{const g=by.get(id),status=g?.status||'NOT-RUN';let detail='No current measurement. Missing evidence is not a pass.';if(g){const m=g.metrics||{};if(id==='V-NM-E')detail=`Reference max error ${m.max_absolute_reference_error?.toExponential(3)??'—'} / tolerance 0.001; crossover ${fmt(m.crossover_ms,2)} ms. Final brief Part III §1.`;else if(g.stale_evidence_reasons?.length)detail=g.stale_evidence_reasons.join('; ');else if(g.failed_checks?.length)detail='Failed: '+g.failed_checks.join(', ');else detail=`${g.checks?.filter(c=>c.status==='PASS').length??0} recorded checks. `+(g.scope||g.kind||'Saved evidence');if(id==='V-NM-ODSP')detail+=' KC target 2–12%; measured odour sparsity remains a biology result.'}if(id==='V-NM-I')detail='NOT-RUN — depends on base V-G/V-H. No substitute visual test.';return `<tr><td>${esc(id)}</td><td><span class="status ${status==='PASS'?'pass':status==='FAIL'?'fail':'notrun'}">${esc(status)}</span></td><td>${esc(detail)}</td></tr>`}).join('');const variant=evidence.stability_variant;if(variant){const rows=[];rows.push('<tr><td colspan="3"><b>Separate whole-brain stability variant</b><br>Original core dynamics and original V-C evidence are unchanged.</td></tr>');for(const run of variant.defaults||[])for(const gate of run.gates||[]){const status=variant.status==='PASS'?gate.status:'NOT-RUN';let detail=`${run.syn_model}; normalization=${run.graded_norm}; κ=${run.kappa}; CT1=${run.ct1_mode}. `;if(gate.gate==='V-C1')detail+=`Relative residual ${gate.relative_residual?.toExponential(3)}, ${gate.iterations} iterations.`;if(gate.gate==='V-C2')detail+=`Growth slope ${gate.slope_per_ms?.toExponential(3)} /ms; τnet=${fmt(gate.tau_net_ms,2)} ms.`;if(gate.gate==='V-C3')detail+=`${gate.clamp_count} clamps; range ${(gate.voltage_range_mV||[]).map(v=>fmt(v,2)).join(' to ')} mV.`;if(gate.gate==='V-C4')detail+=`Half-dt endpoint difference ${gate.max_perturbed_endpoint_difference_mV?.toExponential(3)} mV.`;if(variant.status!=='PASS')detail+=(variant.stale_evidence_reasons||['Parent evidence is not a current PASS']).join('; ');rows.push(`<tr><td>${esc(gate.gate)} · ${esc(run.syn_model)}</td><td><span class="status ${status==='PASS'?'pass':status==='FAIL'?'fail':'notrun'}">${esc(status)}</span></td><td>${esc(detail)}</td></tr>`)}$('gate-table').querySelector('tbody').insertAdjacentHTML('beforeend',rows.join(''))}browserReferenceCheck(evidence.reference);browserFieldCheck(evidence.field_reference)}
function browserReferenceCheck(ref){const card=$('self-check');if(!ref?.curve?.delta_w||!ref.fixture?.given){card.querySelector('strong').textContent='NOT RUN · no Python reference export';card.querySelector('p').textContent='No matching fixture is available for this view.';card.style.borderColor='#3b4b60';return}const f=ref.fixture.given,delays=ref.curve.delays_ms;let max=0;for(let j=0;j<delays.length;j++){let c=0,ep=0,ed=0,w=1;const ac=Math.exp(-1/400),ap=Math.exp(-1/600),ad=Math.exp(-1/1500),on=3000+delays[j];for(let t=0;t<7000;t++){const r=t>=3000&&t<4000?1:0,dr=t>=on&&t<on+500?1:0;c=c*ac+dr*(1-ac);ep=ep*ap+r*(1-ap);ed=ed*ad+c*(1-ad);w-=.00055*(c*ep-.55*r*ed)}max=Math.max(max,Math.abs(w-1-ref.curve.delta_w[j]))}const pass=finite(max)&&max<1e-9;card.querySelector('strong').textContent=(pass?'PASS':'FAIL')+' · browser ↔ Python pinned reference';card.querySelector('p').textContent=`Twelve independently integrated points. Maximum discrepancy ${max.toExponential(3)}; tolerance 1e-9. This is a software cross-check, not a biology gate.`;card.style.borderColor=pass?'#315b52':'#8a6243'}
function nativeDownload(url,name){const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();setTimeout(()=>a.remove(),1000)}
async function download(blob,name){if(!blob)return toast('Figure encoding failed; no file was saved.',true);try{const body={filename:name,content_type:name.endsWith('.csv')?'text/csv':'image/png',context:{config_hash:snapshot.config_hash??null,seed:snapshot.seed??null,t_sim_ms:snapshot.t_sim_ms??null,recorded,selection}};if(body.content_type==='text/csv')body.text=await blob.text();else body.base64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(blob)});const response=await fetch('/api/exports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!response.ok)throw Error('Server export returned '+response.status);const saved=await response.json(),panel=$('export-links');panel.hidden=false;const row=document.createElement('div');row.innerHTML=`Saved <a href="${esc(saved.url)}" download>${esc(saved.filename)}</a> · ${saved.bytes.toLocaleString()} bytes <span>${esc(saved.path)}</span>`;panel.prepend(row);while(panel.children.length>6)panel.lastElementChild.remove();nativeDownload(saved.url,saved.filename);toast('Export saved under runs/exports. Use the persistent link above if the browser does not download automatically.')}catch(error){const url=URL.createObjectURL(blob);nativeDownload(url,name);setTimeout(()=>URL.revokeObjectURL(url),60000);toast('Server storage unavailable. Requested a native browser download; verify it in your downloads.',true)}}

$('export-window').onclick=()=>{const end=history.at(-1)?.t_sim_ms;if(!finite(end))return toast('No measured window to export.');const rows=history.filter(s=>selection?s.t_sim_ms>=selection[0]&&s.t_sim_ms<=selection[1]:s.t_sim_ms>=end-Number($('window').value)),ci=Math.max(0,metadata.compartments?.indexOf($('field-compartment').value)??3),si=Math.max(0,metadata.species?.indexOf($('timeline-species').value)??0);const columns=['t_sim_ms','odour','valence','kc_active_fraction',($('timeline-species').value||'DA')+'_'+($('field-compartment').value||'g4')+'_au','voltage_min_mV','voltage_max_mV','config_hash'];if(!rows.length)return toast('Selected interval has no measured samples.');const csv=[columns.join(','),...rows.map(s=>[s.t_sim_ms,s.controls?.odour||'',s.valence??'',s.kc_active_fraction??'',s.concentrations_au?.[si]?.[ci]??'',s.voltage_min_mV??'',s.voltage_max_mV??'',s.config_hash||''].map(v=>'"'+String(v).replaceAll('"','""')+'"').join(','))].join('\n');download(new Blob([csv],{type:'text/csv'}),'cognesia-window.csv');const source=$('timeline-canvas'),out=document.createElement('canvas');out.width=source.width;out.height=source.height+55;const ctx=out.getContext('2d');ctx.fillStyle='#0b111b';ctx.fillRect(0,0,out.width,out.height);const scale=devicePixelRatio||1;ctx.save();ctx.scale(scale,scale);drawTimeline({context:ctx,width:source.width/scale,height:source.height/scale,bounds:[rows[0].t_sim_ms,rows.at(-1).t_sim_ms]});ctx.restore();ctx.fillStyle='#aebfce';ctx.font='12px monospace';ctx.fillText(`MODEL — NOT A FLY | cfg ${(snapshot.config_hash||'unavailable').slice(0,16)} | seed ${snapshot.seed??'—'} | measured ${rows[0].t_sim_ms}–${rows.at(-1).t_sim_ms} ms`,16,source.height+24);ctx.fillText('Same sample interval as CSV; no interpolation. Assumed field/weight traces are dashed.',16,source.height+43);out.toBlob(blob=>download(blob,'cognesia-window.png'));toast('Saving the measured window and captioned figure…')};
async function unzip(file){const buffer=await file.arrayBuffer(),bytes=new Uint8Array(buffer),view=new DataView(buffer);let end=bytes.length-22;while(end>=Math.max(0,bytes.length-65558)&&view.getUint32(end,true)!==0x06054b50)end--;if(end<0)throw Error('Invalid ZIP directory');let offset=view.getUint32(end+16,true),n=view.getUint16(end+10,true);const output={};for(let i=0;i<n;i++){if(view.getUint32(offset,true)!==0x02014b50)throw Error('Invalid ZIP entry');const method=view.getUint16(offset+10,true),compressed=view.getUint32(offset+20,true),nameLength=view.getUint16(offset+28,true),extra=view.getUint16(offset+30,true),comment=view.getUint16(offset+32,true),local=view.getUint32(offset+42,true);const name=new TextDecoder().decode(bytes.slice(offset+46,offset+46+nameLength));if(/(^|\/)(frames\.jsonl|metadata\.json|.*\.jsonl)$/.test(name)&&!name.includes('events')){const start=local+30+view.getUint16(local+26,true)+view.getUint16(local+28,true),data=bytes.slice(start,start+compressed);if(method===0)output[name]=new TextDecoder().decode(data);else if(method===8){const stream=new Blob([data]).stream().pipeThrough(new DecompressionStream('deflate-raw'));output[name]=await new Response(stream).text()}else throw Error('Unsupported ZIP compression')}offset+=46+nameLength+extra+comment}return output}
$('load-recording').onclick=()=>$('recording-file').click();
$('recording-file').accept='.zip,.json,.jsonl';$('recording-file').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;let frames,meta;if(file.name.endsWith('.zip')){const files=await unzip(file);const name=Object.keys(files).find(x=>x.endsWith('frames.jsonl'));if(!name)throw Error('Archive has no measured frames.jsonl');frames=files[name].trim().split(/\r?\n/).filter(Boolean).map(x=>JSON.parse(x));const mn=Object.keys(files).find(x=>x.endsWith('metadata.json'));if(mn)meta=JSON.parse(files[mn])}else{const text=await file.text();try{const doc=JSON.parse(text);frames=Array.isArray(doc)?doc:doc.frames;meta=doc.metadata}catch{frames=text.trim().split(/\r?\n/).filter(Boolean).map(x=>JSON.parse(x))}}if(!Array.isArray(frames)||!frames.length||frames.some(x=>!finite(x.t_sim_ms)))throw Error('Recording needs measured frames with t_sim_ms');enterRecording(frames,meta,file.name);toast(`Loaded ${frames.length.toLocaleString()} recorded frames. No live engine required.`)}catch(e){toast(e.message,true)}};
function enterRecording(frames,meta,name){
 recorded=true;ws?.close();clearInterval(recordTimer);recordTimer=null;
 snapshot={};metadata={};evidence={};history=[];layout=[];lastFrame=-1;metadataReady=false;
 rasterData=null;weightData=null;atlasPoints=[];atlasBounds=null;selection=null;playhead=null;dragStart=null;
 recordedFrames=frames;recordIndex=0;
 document.querySelectorAll('.write input,.write button,.write select,#run-protocol').forEach(el=>el.disabled=true);
 for(const id of ['intensity-value','dan-value','oa-value','serotonin-value','energy-value','hydration-value','field-value'])$(id).textContent='—';
 for(const id of ['timeline-species','raster-subtype','dan-type','field-species','field-compartment','atlas-species','weight-compartment','weight-subtype'])$(id).innerHTML='<option value="">Metadata unavailable</option>';
 $('core-count').textContent='—';$('mbon-meters').innerHTML='';$('weight-table').querySelector('tbody').innerHTML='';
 $('compartment-warning').textContent='Source annotations require metadata from this recording.';
 $('limitations').innerHTML='<p>Only this recording’s supplied frames and metadata are shown. Matching gate evidence is not included in this archive.</p>';
 $('atlas-tip').hidden=true;canvas2d('raster-canvas');canvas2d('atlas-overlay');
 $('raster-note').textContent='No per-neuron raster loaded for this recording. Binary spike logs remain in the original archive.';
 $('weight-note').textContent='No per-edge snapshot loaded for this recording. Endpoint weights remain in the original archive.';
 $('playhead').textContent='Click to inspect a recorded sample; drag to select an interval.';
 showEvidence({});if(meta)applyMetadata(meta);
 $('connection').textContent='◉ RECORDED SESSION';$('connection').classList.remove('live');$('run-label').textContent=name;
 showRecorded(0);
}
function showRecorded(i){recordIndex=i;const frame=recordedFrames[i];if(!frame)return;snapshot={};updateStatus({...frame,paused:!recordTimer});addSample(frame);requestRender()}
new ResizeObserver(requestRender).observe(document.querySelector('.workspace'));
async function boot(){try{const [s,m,e]=await Promise.all([fetch('/api/status').then(x=>x.json()),fetch('/api/metadata').then(x=>x.json()),fetch('/api/evidence').then(x=>x.json())]);if(recorded)return;applyMetadata(m);showEvidence(e);updateStatus(s);connect();if(!metadataReady){const timer=setInterval(async()=>{if(recorded){clearInterval(timer);return}try{const current=await fetch('/api/metadata').then(x=>x.json());if(recorded){clearInterval(timer);return}applyMetadata(current);if(metadataReady)clearInterval(timer)}catch{}},1000)}}catch(e){if(recorded)return;$('connection').textContent='○ OFFLINE';$('notice').textContent='No engine connected. Load an exported session to inspect measured activity.'}}
boot();
function atlasActivity(i){const j=metadata.atlas?.sample_indices?.indexOf(i);return j>=0?`Actual sample: ${fmt(snapshot.atlas_rates_hz?.[j],2)} Hz · ${fmt(snapshot.atlas_voltage_mV?.[j],2)} mV`:'Activity: unsampled / unavailable'}
for(const id of ['atlas-mode','atlas-species','atlas-hulls'])$(id).onchange=requestRender;
function timelineTime(event){const box=$('timeline-canvas').getBoundingClientRect(),duration=Number($('window').value),end=history.at(-1)?.t_sim_ms||duration,start=Math.max(0,end-duration);return start+Math.max(0,Math.min(1,(event.clientX-box.left-100)/(box.width-116)))*duration}
$('timeline-canvas').onpointerdown=e=>{if(!history.length)return;dragStart=timelineTime(e);e.target.setPointerCapture(e.pointerId)};
$('timeline-canvas').onpointerup=e=>{if(dragStart===null)return;const end=timelineTime(e),sample=history.reduce((a,b)=>Math.abs(b.t_sim_ms-end)<Math.abs(a.t_sim_ms-end)?b:a);playhead=sample.t_sim_ms;if(Math.abs(end-dragStart)>Number($('window').value)*.008)selection=[Math.min(end,dragStart),Math.max(end,dragStart)];$('playhead').textContent=`Sample ${fmt(playhead/1000,3)} s · ${sample.controls?.odour||'unavailable'} · valence ${fmt(sample.valence,3)}${selection?` | export interval ${fmt(selection[0]/1000,3)}–${fmt(selection[1]/1000,3)} s`:''}`;dragStart=null;requestRender()};
$('clear-selection').onclick=()=>{selection=null;playhead=null;$('playhead').textContent='Click to inspect a measured sample; drag to select an interval.';requestRender()};
function drawLearningHistory(){const [ctx,w,h]=canvas2d('learning-canvas'),end=history.at(-1)?.t_sim_ms||0,start=Math.max(0,end-Number($('window').value)),data=history.filter(x=>x.t_sim_ms>=start),values=data.flatMap(x=>x.weights_relative||[]).filter(finite),extent=Math.max(.005,...values.map(v=>Math.abs(v-1))),x=t=>42+(t-start)/Math.max(1,end-start)*(w-55),y=v=>h/2-(v-1)/extent*(h/2-20);ctx.strokeStyle='#415164';ctx.setLineDash([3,3]);ctx.beginPath();ctx.moveTo(42,y(1));ctx.lineTo(w-10,y(1));ctx.stroke();ctx.setLineDash([]);for(const s of data)(s.weights_relative||[]).forEach((v,i)=>{if(!finite(v))return;ctx.fillStyle=palette[i%15];ctx.fillRect(x(s.t_sim_ms),y(v),1.6,1.6)});ctx.fillStyle='#91a5b9';ctx.font='9px ui-monospace';ctx.fillText('w/w₀',1,12);ctx.fillText('1.000',1,h/2+3);ctx.fillText(fmt(start/1000,1)+'s',42,h-3);ctx.fillText(fmt(end/1000,1)+'s',w-45,h-3);const f=metadata.forgetting,ci=metadata.compartments?.indexOf($('field-compartment').value),c=snapshot.concentrations_au?.[0]?.[ci],half=f&&finite(c)?Math.log(2)*f.tau_forget_ms/(1+f.beta*c):null;$('forgetting-note').textContent=`Actual sampled compartment weights; no interpolation. ${f?`Forgetting ASSUMPTION: τ=${fmt(f.tau_forget_ms/1000,1)} s, β=${fmt(f.beta,2)}. Instantaneous frozen-DA half-life in ${$('field-compartment').value}: ${fmt(finite(half)?half/1000:null,2)} s; changing concentration and ongoing learning alter the trajectory.`:'Forgetting parameters unavailable in this recording.'}`}
$('weight-fetch').onclick=async()=>{if(recorded)return toast('Raw edge snapshots are available from the live engine or exported endpoint.npz; loaded summary frames have no per-edge history.');try{const r=await fetch('/api/weights?'+new URLSearchParams({compartment:$('weight-compartment').value,kc_type:$('weight-subtype').value,limit:'200'}));const received=await r.json();if(recorded)return;weightData=received;if(!r.ok)throw Error(weightData.error);$('weight-note').textContent=`${weightData.returned_edges} of ${weightData.matching_edges.toLocaleString()} matching actual edges at ${fmt(weightData.t_sim_ms/1000,3)} s. First indexed edges; not a random sample. ${weightData.weight_unit}.`;$('weight-table').querySelector('tbody').innerHTML=weightData.rows.map(r=>`<tr><td><code>${esc(r.pre_root_id)}<br>→ ${esc(r.post_root_id)}</code></td><td>${esc(r.kc_type)} → ${esc(r.mbon_type)} / ${esc(r.compartment)}</td><td>${fmt(r.baseline,3)}</td><td>${fmt(r.weight,5)}</td><td>${fmt(r.change,5)}</td></tr>`).join('')}catch(e){toast(e.message,true)}};
$('weight-csv').onclick=()=>{if(!weightData?.rows.length)return toast('Read a measured edge snapshot first.');const keys=Object.keys(weightData.rows[0]),csv=[keys.join(','),...weightData.rows.map(row=>keys.map(k=>'"'+String(row[k]??'').replaceAll('"','""')+'"').join(','))].join('\n');download(new Blob([csv],{type:'text/csv'}),`cognesia-edges-${weightData.t_sim_ms}ms.csv`)};
function browserFieldCheck(ref){const card=$('field-self-check');if(!card)return;if(!ref?.fixtures?.length){card.querySelector('strong').textContent='NOT RUN · no current field reference';card.querySelector('p').textContent='No matching field fixture is available for this view.';card.style.borderColor='#3b4b60';return}let error=0;for(const f of ref.fixtures){let c=0,peak=0,a=Math.exp(-f.dt_mod_ms/f.tau_clear_ms);for(let t=0;t<f.end_ms;t+=f.dt_mod_ms){c=c*a+(t<f.pulse_ms?f.source_gain:0)*(1-a);peak=Math.max(peak,c)}error=Math.max(error,Math.abs(c-f.final_au),Math.abs(peak-f.peak_au))}const pass=finite(error)&&error<1e-5;card.querySelector('strong').textContent=(pass?'PASS':'FAIL')+' · browser ↔ Python field decay';card.querySelector('p').textContent=`Eight unit-source, 500 ms pulse / 1000 ms horizon numerical fixtures. Maximum error ${error.toExponential(3)}; tolerance 1e-5. Model concentration, not measured biology.`;card.style.borderColor=pass?'#315b52':'#8a6243'}
$('refresh-evidence').onclick=async()=>{if(recorded)return toast('Matching gate evidence is not included in this recording; live evidence cannot certify it.');try{const current=await fetch('/api/evidence').then(r=>r.json());if(recorded)return;showEvidence(current);toast('Reloaded saved evidence with current provenance checks.')}catch(e){toast(e.message,true)}};
$('archives').onclick=async()=>{try{const rows=await fetch('/api/sessions').then(r=>r.json());const existing=$('session-list');if(existing){existing.remove();return}const panel=document.createElement('dialog');panel.id='session-list';panel.innerHTML='<h2>Sealed sessions</h2><p>Endpoints are sealed before reset and protocol replacement.</p><div class="table-scroll"><table><tbody>'+rows.slice().reverse().map(r=>`<tr><td><a href="/api/sessions/${encodeURIComponent(r.id)}">${esc(r.id)}</a></td><td>${fmt(r.duration_ms/1000,3)} s · seed ${r.seed}</td><td>${esc(r.reason)}</td></tr>`).join('')+'</tbody></table></div><p>'+(rows.length?'':'No session has been sealed yet.')+'</p><button id="close-sessions">Close</button>';document.body.append(panel);$('close-sessions').onclick=()=>panel.remove();panel.showModal()}catch(e){toast(e.message,true)}};
