/** Full-resolution NeuroMechFly body with the application's recorded brain data.
 * No engine, oscillator, autonomous pose, particle stream, or inferred signal.
 * The mesh is source anatomy; cross-animal brain placement is an explicit assumption.
 */
export function fitBrainToHead({positions, visibleIndices, headBounds}) {
  if (!positions || positions.length % 3) throw new Error('Brain positions must contain xyz triples.');
  if(!Array.isArray(headBounds)||headBounds.length!==2||headBounds.some(row=>row.length!==3||row.some(v=>!Number.isFinite(v)))||headBounds[0].some((v,j)=>v>=headBounds[1][j]))throw new Error('Head bounds must be finite, ordered xyz extents.');
  const count=positions.length/3, ids=visibleIndices?Array.from(visibleIndices):Array.from({length:count},(_,i)=>i);
  const valid=ids.filter(i=>Number.isInteger(i)&&i>=0&&i<count&&[0,1,2].every(j=>Number.isFinite(positions[3*i+j])));
  if (!valid.length) throw new Error('No finite anatomical brain positions.');
  const lo=[Infinity,Infinity,Infinity],hi=[-Infinity,-Infinity,-Infinity];
  for(const i of valid)for(let j=0;j<3;j++){lo[j]=Math.min(lo[j],positions[3*i+j]);hi[j]=Math.max(hi[j],positions[3*i+j]);}
  const center=lo.map((v,j)=>(v+hi[j])/2),headCenter=headBounds[0].map((v,j)=>(v+headBounds[1][j])/2);
  // Source brain +x (right) -> fly -y, brain +y -> fly +x, brain +z -> fly +z.
  // Uniform scale retains relative neuron geometry; bounding-box fit is not registration.
  const extent=hi.map((v,j)=>Math.max(v-lo[j],1e-12)),space=headBounds[1].map((v,j)=>(v-headBounds[0][j])*[.65,.77,.65][j]);
  const scale=Math.min(space[0]/extent[1],space[1]/extent[0],space[2]/extent[2]);
  const fitted=new Float32Array(positions.length);
  for(const i of valid){fitted[3*i]=headCenter[0]+(positions[3*i+1]-center[1])*scale;fitted[3*i+1]=headCenter[1]-(positions[3*i]-center[0])*scale;fitted[3*i+2]=headCenter[2]+(positions[3*i+2]-center[2])*scale;}
  return {positions:fitted,visibleIndices:Uint32Array.from(valid),scale,headCenter,sourceCenter:center,neuronCount:count};
}

export function validateFlyFrame(frame, neuronCount) {
  if(!frame?.hasRecording)return {active:false,reason:'Anatomy only · no recorded activity'};
  if(!frame.values || frame.values.length!==neuronCount)return {active:false,reason:'Recorded activity unavailable: neuron count mismatch'};
  if(!Number.isFinite(frame.timeMs))return {active:false,reason:'Recorded activity unavailable: missing model time'};
  if(!['absolute','baseline','delta','chemical','electrical','current','anatomy'].includes(frame.mode))return {active:false,reason:'Recorded activity unavailable: unsupported channel'};
  return {active:frame.mode!=='anatomy',reason:frame.mode==='anatomy'?'Anatomical brain · recorded channel hidden':''};
}

export function createFlyBodyPanel({THREE, OrbitControls, host, assetBase='/assets/fly/', positions=null, visibleIndices=null}) {
  if(!THREE||!OrbitControls||!host)throw new Error('Fly body requires THREE, OrbitControls and a host element.');
  host.classList.add('fly-body-panel');
  host.innerHTML=`<div class="fly-body-heading"><div><span class="fly-body-eyebrow">WHOLE FLY · SCANNED ANATOMY</span><h2>A transparent view of the animal.</h2></div><span class="fly-body-quality">FULL-RESOLUTION SURFACES</span></div>
  <div class="fly-body-tools"><div class="fly-body-display" role="group" aria-label="Fly surface display"><button data-fly-look="ghost" class="active" type="button">Transparent body</button><button data-fly-look="solid" type="button">Natural surface</button></div><label>Body opacity <input data-fly-opacity type="range" min="5" max="100" value="20" aria-label="Fly body opacity"><output data-fly-opacity-value>20%</output></label><label><input data-fly-brain type="checkbox" checked> Brain</label><label><input data-fly-labels type="checkbox" checked> Labels</label><button data-fly-focus type="button">Focus brain</button><button data-fly-reset type="button">Whole fly</button></div>
  <div class="fly-body-stage"><div class="fly-body-viewport"></div><div class="fly-body-loading" role="status">Loading original NeuroMechFly surfaces…</div><div class="fly-body-labels" aria-label="Anatomical landmarks"></div><div class="fly-body-caption"><span data-fly-frame>Anatomy only · no recorded activity</span><span>Drag to orbit · scroll to inspect</span></div></div>
  <div class="fly-body-footnote"><span data-fly-geometry>Source geometry loading</span><span>Brain placement: approximate cross-animal alignment, not anatomical co-registration.</span></div>
  <details class="fly-body-provenance"><summary>Geometry, recording and alignment provenance</summary><p>Body surfaces: NeuroMechFly v2, based on an adult female fly micro-CT scan. Full-resolution source triangles, segmented appendages and official neutral pose are retained. Colors and studio lighting are illustrative; no new hairs, facets or moving particles are fabricated.</p><p>FlyWire neurons come from the original whole-brain view in released index order. A uniform fit places their actual relative coordinates inside the head; the specimens are different animals. Model compartment fields and neuron voltages color these same recorded points. This body has no validated motor decoder and does not act out neural activity.</p><a href="${assetBase}manifest.json" target="_blank" rel="noopener">Mesh manifest &amp; hashes</a><a href="${assetBase}NOTICE.md" target="_blank" rel="noopener">Attribution &amp; alignment</a><a href="${assetBase}LICENSE-APACHE-2.0.txt" target="_blank" rel="noopener">Apache-2.0</a></details>`;
  const q=s=>host.querySelector(s),stage=q('.fly-body-stage'),viewport=q('.fly-body-viewport'),labelLayer=q('.fly-body-labels');
  // Retain controls when the workspace moves them into the inspector.
  const opacityInput=q('[data-fly-opacity]'),opacityValue=q('[data-fly-opacity-value]'),brainToggle=q('[data-fly-brain]'),labelsToggle=q('[data-fly-labels]'),surfaceButtons=[...host.querySelectorAll('[data-fly-look]')];
  const svgNS='http://www.w3.org/2000/svg',leaders=document.createElementNS(svgNS,'svg');leaders.classList.add('fly-body-leaders');leaders.setAttribute('aria-hidden','true');labelLayer.append(leaders);
  let disposed=false,manifest=null,raf=null,bodyMode='ghost',opacity=.2,brainData=null,pendingBrain=positions?{positions,visibleIndices}:null,pendingFrame={hasRecording:false},brain=null,brainMaterial=null;
  const meshes=[],materials=[],geometries=[],landmarks=[];
  const renderHealth={rafCalls:0,draws:0,resizeCalls:0,errors:[],shaderErrors:[]};
  const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(34,1,.01,100);
  camera.up.set(0,0,1);
  const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance',preserveDrawingBuffer:!!window.__COGNESIA_DESKTOP__});
  renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,2));renderer.setClearColor(0xf1f2ee,0);
  renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;
  renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;viewport.append(renderer.domElement);
  renderer.domElement.setAttribute('aria-label','Full-resolution anatomical fruit fly with recorded brain overlay');renderer.domElement.dataset.renderState='ready';
  renderer.debug.onShaderError=(gl,program,vertex,fragment)=>{renderHealth.shaderErrors.push({program:gl.getProgramInfoLog(program),vertex:gl.getShaderInfoLog(vertex),fragment:gl.getShaderInfoLog(fragment)});renderHealth.shaderErrors=renderHealth.shaderErrors.slice(-3);};
  const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.12;controls.minDistance=.18;controls.maxDistance=15;controls.enablePan=true;controls.autoRotate=false;
  const hemisphere=new THREE.HemisphereLight(0xf2f7ff,0x6e5941,2.0);scene.add(hemisphere);
  const key=new THREE.DirectionalLight(0xffedcf,3.5);key.position.set(3,-4,7);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.camera.left=-4;key.shadow.camera.right=4;key.shadow.camera.top=4;key.shadow.camera.bottom=-4;key.shadow.camera.near=.1;key.shadow.camera.far=15;key.shadow.normalBias=.025;scene.add(key);
  const fill=new THREE.DirectionalLight(0xbadfff,1.5);fill.position.set(-2,4,3);scene.add(fill);
  const rim=new THREE.DirectionalLight(0xfff5df,2.0);rim.position.set(-4,-1,5);scene.add(rim);
  const ground=new THREE.Mesh(new THREE.PlaneGeometry(20,20),new THREE.ShadowMaterial({color:0x586169,opacity:.14}));ground.receiveShadow=true;scene.add(ground);geometries.push(ground.geometry);materials.push(ground.material);
  function requestDraw(){if(disposed||raf!==null)return;raf=requestAnimationFrame(()=>{raf=null;renderHealth.rafCalls++;if(disposed)return;controls.update();const box=stage.getBoundingClientRect();if(box.width&&box.height&&!renderer.getContext().isContextLost()){renderer.render(scene,camera);renderHealth.draws++;renderer.domElement.dataset.renderState='drawn';renderer.domElement.dataset.lastDrawMs=String(Math.round(performance.now()));positionLabels(box.width,box.height);}});}
  function redrawWhenVisible(){if(!disposed&&document.visibilityState!=='hidden'){resize();requestDraw();}}
  document.addEventListener('visibilitychange',redrawWhenVisible);window.addEventListener('pageshow',redrawWhenVisible);window.addEventListener('focus',redrawWhenVisible);
  renderer.domElement.addEventListener('webglcontextlost',event=>{event.preventDefault();renderer.domElement.dataset.renderState='context-lost';});
  renderer.domElement.addEventListener('webglcontextrestored',()=>{renderer.domElement.dataset.renderState='restored';redrawWhenVisible();});
  controls.addEventListener('change',requestDraw);
  function resize(){renderHealth.resizeCalls++;if(disposed)return;const {width,height}=stage.getBoundingClientRect();if(width<=0||height<=0)return;renderer.setSize(width,height,false);camera.aspect=width/height;camera.updateProjectionMatrix();requestDraw();}
  const observer=new ResizeObserver(resize);observer.observe(stage);
  function boundsCenter(bounds){return bounds[0].map((v,j)=>(v+bounds[1][j])/2);}
  function resetCamera(head=false){if(!manifest)return;const target=head?boundsCenter(manifest.head_bounds):boundsCenter(manifest.bounds);if(!head)target[2]+=.08;controls.target.fromArray(target);const bounds=head?manifest.head_bounds:manifest.bounds,direction=new THREE.Vector3(.9,-1.05,.65).normalize(),right=new THREE.Vector3().crossVectors(new THREE.Vector3(0,0,1),direction).normalize(),up=new THREE.Vector3().crossVectors(direction,right),tanY=Math.tan(camera.fov*Math.PI/360)*.83,tanX=tanY*camera.aspect;let distance=0;for(let i=0;i<8;i++){const point=new THREE.Vector3(bounds[(i>>0)&1][0]-target[0],bounds[(i>>1)&1][1]-target[1],bounds[(i>>2)&1][2]-target[2]),depth=point.dot(direction);distance=Math.max(distance,Math.abs(point.dot(right))/tanX+depth,Math.abs(point.dot(up))/tanY+depth);}camera.position.fromArray(target).addScaledVector(direction,distance);controls.update();requestDraw();}
  function setSurface(){for(const entry of meshes){const {mesh,name}=entry,mat=mesh.material,isWing=name.includes('wing'),isEye=name.endsWith('_eye'),isHead=name==='c_head';const ghost=bodyMode==='ghost';mat.opacity=ghost?(isWing?opacity*.38:isEye?Math.max(.12,opacity*.7):isHead?opacity*.7:opacity):isWing?.40:1;mat.transparent=ghost||isWing;mat.depthWrite=!ghost&&!isWing;mat.roughness=isWing?.22:isEye?.26:.55;mat.clearcoat=isEye?.45:.18;mat.needsUpdate=true;mesh.castShadow=!ghost||opacity>.65;mesh.renderOrder=ghost?2:0;}opacityValue.textContent=`${Math.round(opacity*100)}%`;opacityInput.disabled=bodyMode==='solid';requestDraw();}
  function landmark(label,segment,offset=[0,0]){const entry=manifest.segments.find(s=>s.name===segment);if(!entry)return;const element=document.createElement('span');element.className='fly-body-landmark';element.textContent=label;labelLayer.append(element);const connector=document.createElementNS(svgNS,'line'),dot=document.createElementNS(svgNS,'circle');dot.setAttribute('r','2');leaders.append(connector,dot);landmarks.push({label,position:new THREE.Vector3(...boundsCenter(entry.bounds)),element,offset,connector,dot});}
  function positionLabels(width,height){leaders.setAttribute('viewBox',`0 0 ${width} ${height}`);for(const item of landmarks){const p=item.position.clone().project(camera),anchorX=(p.x+1)*width/2,anchorY=(1-p.y)*height/2,x=anchorX+item.offset[0],y=anchorY+item.offset[1];item.element.hidden=!labelsToggle.checked||p.z<-1||p.z>1||x<3||x>width-50||y<3||y>height-30;item.element.style.transform=`translate(${x}px,${y}px)`;item.connector.style.display=item.dot.style.display=item.element.hidden?'none':'';if(item.element.hidden)continue;const edgeX=Math.min(Math.max(anchorX,x),x+item.element.offsetWidth),edgeY=Math.min(Math.max(anchorY,y),y+item.element.offsetHeight);for(const [key,value]of Object.entries({x1:anchorX,y1:anchorY,x2:edgeX,y2:edgeY}))item.connector.setAttribute(key,String(value));item.dot.setAttribute('cx',String(anchorX));item.dot.setAttribute('cy',String(anchorY));}}
  function rebuildBrain(){if(!manifest||!pendingBrain||disposed)return;if(brain){scene.remove(brain);brain.geometry.dispose();brain.material.dispose();}
    brainData=fitBrainToHead({...pendingBrain,headBounds:manifest.head_bounds});const geom=new THREE.BufferGeometry();geom.setAttribute('position',new THREE.BufferAttribute(brainData.positions,3));geom.setIndex(new THREE.BufferAttribute(brainData.visibleIndices,1));geom.setAttribute('recordedValue',new THREE.BufferAttribute(new Float32Array(brainData.neuronCount),1).setUsage(THREE.DynamicDrawUsage));
    brainMaterial=new THREE.ShaderMaterial({transparent:true,depthWrite:false,depthTest:true,uniforms:{uActive:{value:0},channel:{value:0},valueRange:{value:1},pointSize:{value:Math.min(window.devicePixelRatio||1,2)*1.45}},vertexShader:`attribute float recordedValue;uniform float uActive;uniform float channel;uniform float valueRange;uniform float pointSize;varying vec3 color;varying float alpha;void main(){float v=recordedValue;bool missing=v<-1e19;float strength=0.;color=vec3(.35,.46,.48);if(uActive>.5&&!missing){if(channel>1.5){strength=clamp(v/max(valueRange,1e-6),0.,1.);color=mix(vec3(.10,.26,.29),vec3(.16,.98,.69),sqrt(strength));}else if(channel>.5){strength=clamp((v+90.)/110.,0.,1.);color=mix(vec3(.12,.42,.92),vec3(1.,.36,.16),strength);}else{strength=clamp(abs(v)/max(valueRange,1e-6),0.,1.);color=mix(vec3(.35,.42,.48),v>=0.?vec3(1.,.32,.14):vec3(.12,.5,1.),sqrt(strength));}}alpha=missing ? .10 : uActive>.5 ? .20+.40*strength : .18;vec4 p=modelViewMatrix*vec4(position,1.);gl_Position=projectionMatrix*p;gl_PointSize=pointSize*(1.+strength*.65);}`,fragmentShader:`varying vec3 color;varying float alpha;void main(){float r=length(gl_PointCoord-vec2(.5))*2.;if(r>1.)discard;gl_FragColor=vec4(color,alpha*(1.-smoothstep(.2,1.,r)));}`});
    brain=new THREE.Points(geom,brainMaterial);brain.renderOrder=1;brain.visible=brainToggle.checked;scene.add(brain);applyFrame();requestDraw();}
  function setBrain(data){pendingBrain=data;if(!data){if(brain){scene.remove(brain);brain.geometry.dispose();brain.material.dispose();}brain=null;brainData=null;brainMaterial=null;q('[data-fly-frame]').textContent='Model anatomy has no registration to this body. Inspect native coordinates in the brain view.';brainToggle.disabled=true;for(const item of landmarks)if(item.label.startsWith('BRAIN'))item.element.textContent='HEAD · unregistered';requestDraw();return;}brainToggle.disabled=false;for(const item of landmarks)if(item.label.startsWith('BRAIN'))item.element.textContent=item.label;rebuildBrain();}
  function applyFrame(){if(!brainData||!brainMaterial)return;const frame=pendingFrame,check=validateFlyFrame(frame,brainData.neuronCount),arr=brain.geometry.attributes.recordedValue.array;brainMaterial.uniforms.uActive.value=check.active?1:0;brainMaterial.uniforms.channel.value=frame.mode==='chemical'?2:['absolute','baseline'].includes(frame.mode)?1:0;brainMaterial.uniforms.valueRange.value=Number.isFinite(frame.range)&&frame.range>0?frame.range:1;
    if(check.active){for(let i=0;i<arr.length;i++){const v=frame.values[i];arr[i]=Number.isFinite(v)&&!(frame.mode==='chemical'&&v<0)?v:-1e30;}brain.geometry.attributes.recordedValue.needsUpdate=true;const channel=frame.label||({absolute:'membrane voltage · mV',baseline:'baseline membrane voltage · mV',delta:'stimulus − baseline · mV',chemical:'compartment field · a.u.',electrical:'recorded electrical drive',current:'recorded electrical drive'}[frame.mode]);q('[data-fly-frame]').textContent=`Recorded ${(frame.timeMs/1000).toFixed(3)} s · ${channel} · no body-motion simulation`;}
    else q('[data-fly-frame]').textContent=check.reason;requestDraw();}
  function setFrame(frame){pendingFrame=frame||{hasRecording:false};applyFrame();return brainData?validateFlyFrame(pendingFrame,brainData.neuronCount):{active:false,reason:'Anatomy loading'};}
  opacityInput.addEventListener('input',event=>{opacity=Number(event.target.value)/100;setSurface();});
  surfaceButtons.forEach(button=>button.addEventListener('click',()=>{bodyMode=button.dataset.flyLook;surfaceButtons.forEach(x=>x.classList.toggle('active',x===button));setSurface();}));
  brainToggle.addEventListener('change',()=>{if(brain)brain.visible=brainToggle.checked;requestDraw();});labelsToggle.addEventListener('change',requestDraw);q('[data-fly-reset]').addEventListener('click',()=>resetCamera(false));q('[data-fly-focus]').addEventListener('click',()=>resetCamera(true));
  const ready=(async()=>{const response=await fetch(assetBase+'manifest.json');if(!response.ok)throw Error('Fly anatomy manifest is unavailable.');manifest=await response.json();const data=await fetch(assetBase+manifest.binary);if(!data.ok)throw Error('Full-resolution fly surfaces are unavailable.');const buffer=await data.arrayBuffer();if(buffer.byteLength!==manifest.bytes)throw Error('Fly mesh byte count differs from manifest.');
    if(globalThis.crypto?.subtle){const hash=await crypto.subtle.digest('SHA-256',buffer),hex=Array.from(new Uint8Array(hash),v=>v.toString(16).padStart(2,'0')).join('');if(hex!==manifest.binary_sha256)throw Error('Fly mesh checksum differs from pinned source conversion.');}
    if(disposed)return;
    const lookup=new Map();for(const [name,entry] of Object.entries(manifest.geometries)){const geom=new THREE.BufferGeometry();geom.setAttribute('position',new THREE.BufferAttribute(new Float32Array(buffer,entry.positions.byte_offset,entry.positions.count),3));geom.setAttribute('normal',new THREE.BufferAttribute(new Float32Array(buffer,entry.normals.byte_offset,entry.normals.count),3));geom.setIndex(new THREE.BufferAttribute(new Uint32Array(buffer,entry.indices.byte_offset,entry.indices.count),1));geom.computeBoundingSphere();lookup.set(name,geom);geometries.push(geom);}
    for(const part of manifest.segments){const rgb=part.color||[.59,.39,.12],mat=new THREE.MeshPhysicalMaterial({color:new THREE.Color().setRGB(rgb[0],rgb[1],rgb[2],THREE.SRGBColorSpace),roughness:.55,metalness:0,clearcoat:.18,side:THREE.DoubleSide,transparent:true,opacity});const mesh=new THREE.Mesh(lookup.get(part.geometry),mat);mesh.name=part.name;mesh.matrixAutoUpdate=false;mesh.matrix.fromArray(part.matrix);mesh.receiveShadow=true;scene.add(mesh);meshes.push({mesh,name:part.name});materials.push(mat);}
    ground.position.z=manifest.bounds[0][2]-.02;setSurface();landmark('HEAD','c_head',[16,-30]);landmark('THORAX','c_thorax',[15,-25]);landmark('ABDOMEN','c_abdomen5',[-60,5]);landmark('WINGS','l_wing',[-20,-35]);landmark('LEGS · 6','lf_tibia',[15,15]);landmark('BRAIN · aligned','c_head',[-125,20]);
    q('.fly-body-loading').hidden=true;q('[data-fly-geometry]').textContent=`${manifest.total_triangles.toLocaleString()} original triangles · ${manifest.segments.length} articulated parts · micro-CT-derived NeuroMechFly`;
    setBrain(pendingBrain);resetCamera(false);resize();return manifest;
  })().catch(error=>{if(!disposed){q('.fly-body-loading').textContent=error.message;q('[data-fly-geometry]').textContent='Source anatomy unavailable — no substitute body generated';}throw error;});
  resize();
  function dispose(){if(disposed)return;disposed=true;if(raf!==null)cancelAnimationFrame(raf);observer.disconnect();document.removeEventListener('visibilitychange',redrawWhenVisible);window.removeEventListener('pageshow',redrawWhenVisible);window.removeEventListener('focus',redrawWhenVisible);controls.dispose();if(brain){brain.geometry.dispose();brain.material.dispose();}for(const g of geometries)g.dispose();for(const m of materials)m.dispose();renderer.dispose();renderer.forceContextLoss();host.replaceChildren();}
  function diagnostics(){const box=stage.getBoundingClientRect(),gl=renderer.getContext();return{...renderHealth,rafQueued:raf!==null,canvas:[renderer.domElement.width,renderer.domElement.height],cssSize:[box.width,box.height],renderState:renderer.domElement.dataset.renderState,contextLost:gl.isContextLost(),contextAttributes:gl.getContextAttributes(),rendererCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,camera:camera.position.toArray(),cameraAspect:camera.aspect,sceneChildren:scene.children.length,loadedMeshes:meshes.length};}
  return {ready,setBrain,setFrame,resize,dispose,diagnostics,requestRender:requestDraw,focusBrain:()=>resetCamera(true),resetCamera:()=>resetCamera(false),get metadata(){return manifest;}};
}
