import { parseEEGCsv, readNiftiFile, niftiVoxelSeries } from "./instrument-data.js";
import { validateRegistration, registeredAnchors } from "./instrument-registration.js";

export function createInstrumentPanel({host,kind="eeg",onSignal,onStatus,getContext=()=>({}),initialState=null}) {
  host.classList.add("instrument-panel");
  const eeg=kind==="eeg";
  host.innerHTML=`<div class="instrument-import"><label>${eeg?"EEG recording (CSV)":"Recorded volume (.nii / .nii.gz)"}<input type="file" accept="${eeg?".csv,text/csv":".nii,.gz"}"></label>${eeg?'<label>Time unit<select class="instrument-time-unit"><option value="auto">From column header</option><option value="s">Seconds</option><option value="ms">Milliseconds</option></select></label><label>Channel unit<select class="instrument-value-unit"><option>as recorded</option><option>µV</option><option>mV</option><option>V</option></select></label>':''}</div><p class="instrument-status" role="status">${eeg?"CSV: time_s or time_ms, then named EEG channels. Set the value unit.":"Scalar NIfTI-1 · file voxel axes. Fly alignment requires registration."}</p><div class="instrument-controls" hidden></div><div class="instrument-stage"><canvas aria-label="${eeg?"Imported EEG traces":"Imported volume cross section"}"></canvas><p class="instrument-empty">${eeg?"No EEG recording imported.":"No imaging volume imported."}</p></div><div class="instrument-detail"></div>`;
  const $=selector=>host.querySelector(selector),canvas=$("canvas"),stage=$(".instrument-stage"),status=$(".instrument-status"),controls=$(".instrument-controls"),detail=$(".instrument-detail");
  let recording=null,volume=null,fileName="",loadVersion=0,disposed=false,contextTime=0,selectedChannel=0,selection=[0,0,0],frame=0,axis=2,contrast=[0,1],sliceRect=null,playTimer=null,registration=null;
  const registrationContext=()=>{const context=getContext();return{modelId:context.modelId||context.metadata?.model_id,modelHash:context.metadata?.model_hash||context.summary?.model_hash,volumeHash:volume?.sha256,dims:volume?.dims};};
  const note=(message,error=false)=>{status.textContent=message;status.classList.toggle("instrument-error",error);if(error)onStatus?.(message);};
  const stop=()=>{if(playTimer!==null)clearInterval(playTimer);playTimer=null;const button=$(".instrument-play");if(button)button.textContent="Play frames";};
  function dimensions(){const w=Math.max(150,Math.floor(stage.clientWidth)),h=Math.max(150,Math.floor(stage.clientHeight));const dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=w*dpr;canvas.height=h*dpr;const ctx=canvas.getContext("2d");ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle="#15181d";ctx.fillRect(0,0,w,h);return{w,h,ctx};}
  function drawEEG(){
    const {w,h,ctx}=dimensions();if(!recording)return;
    const count=Math.min(8,recording.channels.length),start=Math.min(selectedChannel,Math.max(0,recording.channels.length-count));
    const left=68,right=w-12,top=14,bottom=h-24,span=recording.timeMs.at(-1)-recording.timeMs[0];
    ctx.font="10px system-ui";
    for(let n=0;n<count;n++){
      const channel=recording.channels[start+n],cy=top+(n+.5)*(bottom-top)/count,band=(bottom-top)/count*.38;
      let min=Infinity,max=-Infinity,sum=0;for(const v of channel.values){min=Math.min(min,v);max=Math.max(max,v);sum+=v;}const mean=sum/channel.values.length,scale=Math.max(max-mean,mean-min)||1;
      ctx.fillStyle=start+n===selectedChannel?"#b7dbf5":"#a7b0c0";ctx.fillText(channel.label.slice(0,12),4,cy+3);
      ctx.strokeStyle="#343943";ctx.beginPath();ctx.moveTo(left,cy);ctx.lineTo(right,cy);ctx.stroke();
      ctx.strokeStyle=start+n===selectedChannel?"#77b8ea":"#92b5cc";ctx.beginPath();
      // Min/max envelopes keep narrow spikes visible when samples exceed pixels.
      let bucket=-1,low=Infinity,high=-Infinity,bx=0;
      const flush=()=>{if(bucket<0)return;ctx.moveTo(bx,cy-(low-mean)/scale*band);ctx.lineTo(bx,cy-(high-mean)/scale*band);};
      if(channel.values.length>(right-left)*2){for(let i=0;i<channel.values.length;i++){const x=left+(recording.timeMs[i]-recording.timeMs[0])/span*(right-left),b=Math.floor(x);if(b!==bucket){flush();bucket=b;bx=x;low=high=channel.values[i];}else{low=Math.min(low,channel.values[i]);high=Math.max(high,channel.values[i]);}}flush();}
      else for(let i=0;i<channel.values.length;i++){const x=left+(recording.timeMs[i]-recording.timeMs[0])/span*(right-left),y=cy-(channel.values[i]-mean)/scale*band;if(i)ctx.lineTo(x,y);else ctx.moveTo(x,y);}
      ctx.stroke();
    }
    if(contextTime>=recording.timeMs[0]&&contextTime<=recording.timeMs.at(-1)){const x=left+(contextTime-recording.timeMs[0])/span*(right-left);ctx.strokeStyle="#ecb56c";ctx.beginPath();ctx.moveTo(x,top);ctx.lineTo(x,bottom);ctx.stroke();}
    ctx.fillStyle="#a7b0c0";ctx.fillText(`${recording.timeMs[0]} ms`,left,h-7);ctx.textAlign="right";ctx.fillText(`${recording.timeMs.at(-1)} ms`,right,h-7);ctx.textAlign="left";
    detail.textContent=`${fileName} · ${recording.sampleCount.toLocaleString()} samples · ${recording.channels.length} channels · ${recording.unit}. Channels are centered and scaled separately. Chart a channel for absolute values.`;
  }
  function drawVolume(){
    const {w,h,ctx}=dimensions();if(!volume)return;
    const axes=[0,1,2].filter(v=>v!==axis),nx=volume.dims[axes[0]],ny=volume.dims[axes[1]],image=new ImageData(nx,ny),pos=[...selection];
    for(let y=0;y<ny;y++)for(let x=0;x<nx;x++){pos[axes[0]]=x;pos[axes[1]]=ny-1-y;const value=volume.valueAt(...pos,frame),i=(x+y*nx)*4,v=Math.round(Math.max(0,Math.min(1,(value-contrast[0])/(contrast[1]-contrast[0])))*255);image.data[i]=image.data[i+1]=image.data[i+2]=v;image.data[i+3]=Number.isFinite(value)?255:0;}
    const source=document.createElement("canvas");source.width=nx;source.height=ny;source.getContext("2d").putImageData(image,0,0);
    const sx=nx*volume.spacing[axes[0]],sy=ny*volume.spacing[axes[1]],scale=Math.min((w-20)/sx,(h-20)/sy),width=sx*scale,height=sy*scale,x=(w-width)/2,y=(h-height)/2;
    ctx.fillStyle="#15181d";ctx.fillRect(0,0,w,h);ctx.imageSmoothingEnabled=false;ctx.drawImage(source,x,y,width,height);sliceRect={x,y,width,height,axes,nx,ny};
    const px=x+(selection[axes[0]]+.5)/nx*width,py=y+(ny-selection[axes[1]]-.5)/ny*height;
    ctx.strokeStyle="#55dad3";ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(px-8,py);ctx.lineTo(px+8,py);ctx.moveTo(px,py-8);ctx.lineTo(px,py+8);ctx.stroke();
    const value=volume.valueAt(...selection,frame),world=volume.voxelToWorld(...selection);
    let overlayNote="File voxel axes · unregistered.";
    if(registration&&$(".instrument-overlay")?.checked){try{const checked=validateRegistration(registration,registrationContext()),context=getContext(),anchors=registeredAnchors({positions:context.positions,visibleIndices:context.visibleIndices,centerUm:context.metadata?.center_um,scaleUm:context.metadata?.scale_um,registration:checked,dims:volume.dims,axis,slice:selection[axis]});ctx.fillStyle="#ffb84d";for(const anchor of anchors){const ax=x+(anchor.voxel[axes[0]]+.5)/nx*width,ay=y+(ny-anchor.voxel[axes[1]]-.5)/ny*height;ctx.beginPath();ctx.arc(ax,ay,anchor.index===context.selectedNeuron?4:1.7,0,Math.PI*2);ctx.fill();}overlayNote=`${anchors.length.toLocaleString()} registered source anchors in ±0.5 voxel slab · user-supplied model/hash-qualified transform.`;}catch(error){overlayNote=`Overlay disabled: ${error.message}`;}}
    detail.textContent=`Voxel (${selection.join(", ")}) · value ${Number.isFinite(value)?Number(value.toPrecision(7)):"missing"} · frame ${frame+1}/${volume.dims[3]}${world?` · world (${world.map(v=>Number(v.toPrecision(5))).join(", ")}) ${volume.spatialUnit}`:""}. ${overlayNote}`;
    $(".instrument-slice-value").textContent=selection[axis];$(".instrument-frame-value").textContent=frame+1;
    const trace=$(".instrument-voxel-trace");if(trace&&volume.dims[3]>1){const context=trace.getContext("2d");trace.width=Math.max(100,detail.clientWidth);trace.height=60;context.fillStyle="#15181d";context.fillRect(0,0,trace.width,trace.height);const values=Array.from({length:volume.dims[3]},(_,t)=>volume.valueAt(...selection,t)),finite=values.filter(Number.isFinite),lo=Math.min(...finite),hi=Math.max(...finite);context.strokeStyle="#77b8ea";context.beginPath();let moved=false;values.forEach((v,i)=>{if(!Number.isFinite(v)){moved=false;return;}const px=i/(values.length-1)*(trace.width-1),py=55-(v-lo)/(hi-lo||1)*50;if(moved)context.lineTo(px,py);else context.moveTo(px,py);moved=true;});context.stroke();}
  }
  const draw=()=>{if(disposed)return;eeg?drawEEG():drawVolume();};
  function buildEEGControls(){controls.replaceChildren();const select=document.createElement("select");select.setAttribute("aria-label","EEG channel");recording.channels.forEach((c,i)=>select.add(new Option(c.label,i)));select.addEventListener("change",()=>{selectedChannel=Number(select.value);draw();});const button=document.createElement("button");button.textContent="Chart selected channel";button.addEventListener("click",()=>{const channel=recording.channels[selectedChannel];onSignal?.({id:`import-eeg:${fileName}:${selectedChannel}`,label:`${fileName} · ${channel.label}`,unit:channel.unit,timeMs:recording.timeMs,values:channel.values,runId:null,description:"Imported EEG recording; no simulated forward model."});});select.value=selectedChannel;controls.append(select,button);}
  function buildVolumeControls(){
    controls.innerHTML='<label>Section<select class="instrument-axis"><option value="2">Voxel XY</option><option value="1">Voxel XZ</option><option value="0">Voxel YZ</option></select></label><label>Slice <span class="instrument-slice-value"></span><input class="instrument-slice" type="range" min="0" step="1"></label><label>Frame <span class="instrument-frame-value"></span><input class="instrument-frame" type="range" min="0" step="1"></label><label>Black<input class="instrument-low" type="number" step="any"></label><label>White<input class="instrument-high" type="number" step="any"></label><button class="instrument-play">Play frames</button><label class="instrument-check"><input type="checkbox" class="instrument-link-time"> Link to simulation time</label><button class="instrument-chart-voxel">Chart voxel</button>';
    const slice=$(".instrument-slice"),frames=$(".instrument-frame");slice.max=volume.dims[axis]-1;slice.value=selection[axis];frames.max=volume.dims[3]-1;frames.value=frame;
    $(".instrument-axis").addEventListener("change",event=>{axis=Number(event.target.value);slice.max=volume.dims[axis]-1;slice.value=selection[axis];draw();});
    slice.addEventListener("input",()=>{selection[axis]=Number(slice.value);draw();});frames.addEventListener("input",()=>{frame=Number(frames.value);draw();});
    $(".instrument-low").value=contrast[0];$(".instrument-high").value=contrast[1];
    for(const selector of [".instrument-low",".instrument-high"])$(selector).addEventListener("change",()=>{const low=Number($(".instrument-low").value),high=Number($(".instrument-high").value);if(Number.isFinite(low)&&Number.isFinite(high)&&high>low){contrast=[low,high];draw();}else note("White level must be greater than black level.",true);});
    $(".instrument-play").disabled=volume.dims[3]<2;$(".instrument-play").addEventListener("click",()=>{if(playTimer!==null){stop();return;}$(".instrument-play").textContent="Pause frames";playTimer=setInterval(()=>{frame=(frame+1)%volume.dims[3];frames.value=frame;draw();},Math.max(80,Math.min(1000,volume.timeStepMs||200)));});
    $(".instrument-link-time").disabled=!volume.timeStepMs;$(".instrument-link-time").title=volume.timeStepMs?"Uses file time units and offset; no physiological alignment.":"NIfTI time units are missing; linking is unavailable.";
    $(".instrument-chart-voxel").disabled=volume.dims[3]<2||!volume.timeStepMs;$(".instrument-chart-voxel").addEventListener("click",()=>{onSignal?.({id:`import-nifti:${fileName}:${selection.join(":")}`,label:`${fileName} voxel (${selection.join(", ")})`,unit:"imported intensity",...niftiVoxelSeries(volume,selection),runId:null,description:"Imported voxel time series, in the file's declared time units and time offset."});});
    const importLabel=document.createElement("label");importLabel.textContent="Registered transform (JSON)";const transformFile=document.createElement("input");transformFile.type="file";transformFile.accept=".json,application/json";transformFile.className="instrument-registration-file";importLabel.append(transformFile);
    const toggleLabel=document.createElement("label"),toggle=document.createElement("input");toggle.type="checkbox";toggle.className="instrument-overlay";toggle.checked=!!registration;toggle.disabled=!registration;toggleLabel.append(toggle,document.createTextNode(" Registered anchors"));toggle.addEventListener("change",draw);
    transformFile.addEventListener("change",async()=>{const file=transformFile.files?.[0];if(!file)return;try{if(file.size>65536)throw new Error("Registration JSON must be smaller than 64 KiB.");registration=validateRegistration(JSON.parse(await file.text()),registrationContext());toggle.disabled=false;toggle.checked=true;note("Registration loaded: model µm → volume voxels.");draw();}catch(error){note(error.message,true);}});
    const template=document.createElement("button");template.textContent="Registration template";template.addEventListener("click",()=>{const c=registrationContext();if(!c.modelHash){note("Active anatomy has no verified model hash; registration is unavailable.",true);return;}const value={schema_version:1,model_id:c.modelId,model_hash:c.modelHash,volume_sha256:c.volumeHash,volume_dims:volume.dims.slice(0,3),source_units:"um",target_units:"voxel",model_um_to_voxel:[[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]],note:"Replace this identity matrix with your measured/calibrated registration. No alignment is inferred."},url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:"application/json"})),link=document.createElement("a");link.href=url;link.download="cognesia-registration-template.json";link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});controls.append(importLabel,toggleLabel,template);
    if(volume.dims[3]>1){const trace=document.createElement("canvas");trace.className="instrument-voxel-trace";trace.setAttribute("aria-label","Selected voxel time course");detail.after(trace);}
  }
  $("input[type=file]").addEventListener("change",async event=>{
    const file=event.target.files?.[0];if(!file)return;const version=++loadVersion;stop();note(`Loading ${file.name}…`);
    try{
      if(eeg){if(file.size>64*1024*1024)throw new Error("Choose an EEG CSV smaller than 64 MiB.");const parsed=parseEEGCsv(await file.text(),{timeUnit:$(".instrument-time-unit").value,unit:$(".instrument-value-unit").value});if(disposed||version!==loadVersion)return;recording=parsed;selectedChannel=0;buildEEGControls();}
      else {const parsed=await readNiftiFile(file);if(disposed||version!==loadVersion)return;if(kind==="fmri"&&parsed.dims[3]<2)throw new Error("fMRI view needs a 4D volume with multiple time frames. Use MRI for a 3D volume.");volume=parsed;registration=null;selection=volume.dims.slice(0,3).map(n=>Math.floor(n/2));axis=2;frame=0;contrast=[volume.low,volume.high];$(".instrument-voxel-trace")?.remove();buildVolumeControls();}
      fileName=file.name;controls.hidden=false;$(".instrument-empty").hidden=true;note(`${fileName} imported locally. ${eeg?"Original values; independent channel scales.":`${volume.dims.join(" × ")} scalar samples from your file.`}`);draw();
    }catch(error){if(version===loadVersion&&!disposed)note(error.message,true);}
  });
  canvas.addEventListener("click",event=>{if(eeg||!volume||!sliceRect)return;const r=canvas.getBoundingClientRect(),x=event.clientX-r.left,y=event.clientY-r.top,b=sliceRect;if(x<b.x||x>=b.x+b.width||y<b.y||y>=b.y+b.height)return;selection[b.axes[0]]=Math.min(b.nx-1,Math.floor((x-b.x)/b.width*b.nx));selection[b.axes[1]]=b.ny-1-Math.min(b.ny-1,Math.floor((y-b.y)/b.height*b.ny));draw();});
  const observer=new ResizeObserver(draw);observer.observe(stage);
  if(initialState&&(initialState.recording||initialState.volume)){recording=initialState.recording;volume=initialState.volume;registration=initialState.registration||null;fileName=initialState.fileName;selectedChannel=initialState.selectedChannel||0;selection=initialState.selection?[...initialState.selection]:[0,0,0];frame=initialState.frame||0;axis=initialState.axis??2;contrast=initialState.contrast?[...initialState.contrast]:[0,1];eeg?buildEEGControls():buildVolumeControls();controls.hidden=false;$(".instrument-empty").hidden=true;note(`Duplicated view: ${fileName}. Shared, unchanged data.`);draw();}
  return {exportInstrumentState(){return{recording,volume,registration,fileName,selectedChannel,selection:[...selection],frame,axis,contrast:[...contrast]};},setTime(ms){contextTime=ms;if(volume&&$(".instrument-link-time")?.checked&&volume.timeStepMs){frame=Math.max(0,Math.min(volume.dims[3]-1,Math.round((ms-(volume.timeOriginMs||0))/volume.timeStepMs)));$(".instrument-frame").value=frame;}draw();},refresh:draw,dispose(){disposed=true;loadVersion++;stop();observer.disconnect();recording=null;volume=null;}};
}
