import { initializeAnalysis } from "./analysis.js";
import { alignedDifference, recordedSpikeEvents, fullModelConnectivityRequest } from "./research-data.js";

export function createChemistryView({host,analysisOptions}) {
  const filter=entries=>entries.filter(entry=>/chemical|state|enzyme|hormone|metabolite/i.test(`${entry.group} ${entry.kind} ${entry.id}`));
  const chart=initializeAnalysis({...analysisOptions,host,autoDefaults:false,listSignals:async()=>filter(await analysisOptions.listSignals())});
  chart.refresh();return chart;
}

export function createSpikeView({host,getContext}) {
  host.classList.add("instrument-panel");host.innerHTML='<p class="instrument-status">Recorded spikes only; not inferred from voltage peaks.</p><div class="instrument-stage"><canvas aria-label="Spike event raster"></canvas></div><p class="instrument-detail"></p>';
  const canvas=host.querySelector("canvas"),stage=host.querySelector(".instrument-stage"),detail=host.querySelector(".instrument-detail"),status=host.querySelector(".instrument-status");let events=[],lastFrame=null,lastSession=null;
  function refresh(){const context=getContext(),frame=context.liveFrame,session=typeof context.session==="string"?context.session:context.session?.id||context.summary?.id||null;
    status.textContent=frame?"Sampled live spikes; skipped display chunks remain in the recording.":"Latest 15,000 recorded spikes; not inferred from voltage peaks.";
    if(session!==lastSession){lastSession=session;events=[];lastFrame=null;}
    if(!frame)events=recordedSpikeEvents(context.summary?.spikes);
    if(frame&&frame!==lastFrame){lastFrame=frame;events.push(...recordedSpikeEvents(frame.spikes||frame));if(events.length>15000)events=events.slice(-15000);}
    const w=Math.max(150,stage.clientWidth),h=Math.max(150,stage.clientHeight);canvas.width=w;canvas.height=h;const ctx=canvas.getContext("2d");ctx.fillStyle="#15181d";ctx.fillRect(0,0,w,h);ctx.font="11px system-ui";ctx.fillStyle="#a7b0c0";
    if(!events.length){ctx.fillText("No recorded spikes in this view.",10,25);detail.textContent="Load or run a recording with spikes.";return;}
    let lo=Infinity,hi=-Infinity,maxNeuron=0;for(const [t,n]of events){lo=Math.min(lo,t);hi=Math.max(hi,t);maxNeuron=Math.max(maxNeuron,n);}const span=hi-lo||1;
    ctx.strokeStyle="#77b8ea";ctx.beginPath();for(const[t,n]of events){const x=45+(t-lo)/span*(w-57),y=14+n/Math.max(1,maxNeuron)*(h-45);ctx.moveTo(x,y-1);ctx.lineTo(x,y+1);}ctx.stroke();ctx.fillText(`${lo.toFixed(1)} ms`,45,h-8);ctx.textAlign="right";ctx.fillText(`${hi.toFixed(1)} ms`,w-10,h-8);ctx.textAlign="left";ctx.fillText("neuron",3,12);detail.textContent=`${events.length.toLocaleString()} actual spike events shown (latest 15,000 maximum) · ${frame?"sampled live chunks":"saved recording"} · neuron index 0–${maxNeuron}.`;
  }
  const observer=new ResizeObserver(refresh);observer.observe(stage);refresh();return{refresh,setTime:refresh,dispose(){observer.disconnect();events=[];}};
}

export function createConnectivityView({host,getContext,onStatus}) {
  host.classList.add("connectivity-instance");host.innerHTML='<div class="connectivity-selectors"><label>Source regions<select multiple data-source aria-label="Source regions"></select><button data-capture-source>Use selected neuron</button></label><label>Target regions<select multiple data-target aria-label="Target regions"></select><button data-capture-target>Use selected neuron</button></label></div><div class="instrument-controls"><button data-query>Inspect connections</button><span data-selection></span></div><p class="instrument-status">Select regions or neurons. Counts use directed model edges.</p><div class="connectivity-table"></div>';
  const $=s=>host.querySelector(s);let sourceIndices=null,targetIndices=null,lastRegions=null,queryToken=0,disposed=false,lastIdentity=null;
  function refresh(){const context=getContext(),identity=`${context.modelId||context.metadata?.model_id}:${context.metadata?.model_hash||context.modelHash}`,regions=context.metadata?.regions;if(identity!==lastIdentity){lastIdentity=identity;sourceIndices=targetIndices=null;queryToken++;$("[data-query]").disabled=false;$("[data-selection]").textContent="";$(".connectivity-table").replaceChildren();}if(regions!==lastRegions){lastRegions=regions;for(const select of [$("[data-source]"),$("[data-target]")]){const prior=new Set([...select.selectedOptions].map(v=>v.value));select.replaceChildren();for(const region of regions||[]){const option=new Option(region.label||region.name||region.key,region.key);option.selected=prior.has(region.key);select.add(option);}}}}
  for(const name of["source","target"]){$(`[data-capture-${name}]`).addEventListener("click",()=>{const neuron=getContext().selectedNeuron;if(!Number.isInteger(neuron)){onStatus?.("Select a neuron in the brain view.");return;}if(name==="source")sourceIndices=[neuron];else targetIndices=[neuron];$(`[data-${name}]`).selectedIndex=-1;$("[data-selection]").textContent=`Source: ${sourceIndices?.join(", ")||"regions"}; target: ${targetIndices?.join(", ")||"regions"}`;});$(`[data-${name}]`).addEventListener("change",()=>{if(name==="source")sourceIndices=null;else targetIndices=null;});}
  $("[data-query]").addEventListener("click",async()=>{
    const token=++queryToken,context=getContext();let request;
    try{request=fullModelConnectivityRequest(context,{sourceIndices,targetIndices,sourceRegions:[...$("[data-source]").selectedOptions].map(v=>v.value),targetRegions:[...$("[data-target]").selectedOptions].map(v=>v.value)});}catch(error){$(".instrument-status").textContent=error.message;onStatus?.(error.message);return;}
    if(!(request.source_indices||request.source_regions)?.length||!(request.target_indices||request.target_regions)?.length){$(".instrument-status").textContent="Select both a source and a target.";return;}
    $("[data-query]").disabled=true;$(".instrument-status").textContent="Reading directed connections…";
    try{if(context.metadata?.regions_url){const membershipResponse=await fetch(context.metadata.regions_url),membership=await membershipResponse.json();if(!membershipResponse.ok)throw new Error("The active model region membership is unavailable.");for(const name of["source","target"]){const keys=request[`${name}_regions`];if(keys){request[`${name}_indices`]=[...new Set(keys.flatMap(key=>{if(!Array.isArray(membership[key]))throw new Error("Selected region is absent from the displayed anatomy.");return membership[key];}))];delete request[`${name}_regions`];}}}const response=await fetch("/api/connectivity",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(request)}),data=await response.json();if(!response.ok)throw new Error(data.error||"Connectivity query failed.");if(disposed||token!==queryToken)return;
      $(".instrument-status").textContent=`Source → target: ${data.forward.edge_count.toLocaleString()} edges, ${data.forward.synapse_count.toLocaleString()} synapses. Target → source: ${data.reverse.edge_count.toLocaleString()} edges, ${data.reverse.synapse_count.toLocaleString()} synapses. Showing at most 100 edges per direction.`;
      const table=document.createElement("table"),head=document.createElement("thead"),row=document.createElement("tr");for(const label of["Direction","Source root ID","Target root ID","Weight","Kind"]){const cell=document.createElement("th");cell.textContent=label;row.append(cell);}head.append(row);table.append(head);const body=document.createElement("tbody");for(const[direction,group]of[["Forward",data.forward],["Reverse",data.reverse]])for(const edge of group.edges||[]){const row=document.createElement("tr");for(const value of[direction,edge.source_id,edge.target_id,edge.weight,edge.kind]){const cell=document.createElement("td");cell.textContent=String(value??"");row.append(cell);}body.append(row);}table.append(body);$(".connectivity-table").replaceChildren(table);
    }catch(error){if(token===queryToken)$(".instrument-status").textContent=error.message;onStatus?.(error.message);}finally{if(token===queryToken&&!disposed)$("[data-query]").disabled=false;}
  });refresh();return{refresh,setTime(){},dispose(){disposed=true;queryToken++;}};
}

export function createBranchComparisonView({host,analysisOptions,onStatus}) {
  host.classList.add("branch-comparison-instance");host.innerHTML='<div class="instrument-controls"><label>Recording A<select data-run-a></select></label><label>Recording B<select data-run-b></select></label><button data-refresh>Refresh recordings</button><label>Recorded population<select data-trace></select></label><label>Channel<select data-channel><option value="raw">Absolute voltage</option><option value="values">Stimulus − baseline</option><option value="baseline">Baseline</option></select></label><button data-compare>Compare</button></div><p class="instrument-status">Compare saved population recordings.</p><div class="branch-comparison-charts"></div>';
  const $=s=>host.querySelector(s),chart=initializeAnalysis({...analysisOptions,host:$(".branch-comparison-charts"),autoDefaults:false});let summaries=new Map(),disposed=false;
  const groups=summary=>[["type",summary.traces],["region",summary.region_traces],["class",summary.class_traces]].flatMap(([kind,data])=>(Array.isArray(data)?data:data?.traces||[]).map(trace=>({...trace,key:`${kind}:${trace.name||trace.label}`})));
  async function summary(id){if(!summaries.has(id)){const response=await fetch(`/api/runs/${encodeURIComponent(id)}/summary.json`),data=await response.json();if(!response.ok)throw new Error(data.error||"Recording unavailable.");summaries.set(id,data);}return summaries.get(id);}
  async function updateTraces(){try{const a=$("[data-run-a]").value,b=$("[data-run-b]").value;if(!a||!b)return;const[sa,sb]=await Promise.all([summary(a),summary(b)]);if(disposed)return;const other=new Set(groups(sb).map(t=>t.key)),prior=$("[data-trace]").value;$("[data-trace]").replaceChildren(...groups(sa).filter(t=>other.has(t.key)).map(t=>new Option(t.name||t.label,t.key)));if([...$("[data-trace]").options].some(o=>o.value===prior))$("[data-trace]").value=prior;}catch(error){$(".instrument-status").textContent=error.message;}}
  async function refresh(){try{const response=await fetch("/api/runs"),data=await response.json();if(!response.ok)throw new Error(data.error||"Recordings unavailable.");if(disposed)return;const runs=Array.isArray(data)?data:data.runs||[];for(const selector of["[data-run-a]","[data-run-b]"]){const select=$(selector),prior=select.value;select.replaceChildren(...runs.map(run=>new Option(run.label||run.id,run.id)));if(runs.some(run=>run.id===prior))select.value=prior;}if($("[data-run-a]").value===$("[data-run-b]").value&&runs.length>1)$("[data-run-b]").selectedIndex=1;await updateTraces();await chart.refresh();}catch(error){if(!disposed)$(".instrument-status").textContent=error.message;}}
  for(const selector of["[data-run-a]","[data-run-b]"])$(selector).addEventListener("change",updateTraces);$("[data-refresh]").addEventListener("click",refresh);
  $("[data-compare]").addEventListener("click",async()=>{try{const ids=[$("[data-run-a]").value,$("[data-run-b]").value],key=$("[data-trace]").value,channel=$("[data-channel]").value,sources=[];let model=null;for(const id of ids){const s=await summary(id),trace=groups(s).find(t=>t.key===key),values=trace?.[channel],timeMs=s.frames?.time_ms;if(model!==null&&model!==(s.model_id||"flywire-783"))throw new Error("Select recordings from the same source model for a population difference.");model=s.model_id||"flywire-783";if(channel!=="raw"&&s.baseline_available===false)throw new Error("This recording has no matched baseline; select absolute voltage.");if(!values||!timeMs||values.length!==timeMs.length)throw new Error("This channel is not recorded consistently in both runs.");sources.push({id:`${key}:${channel}`,label:`${s.label||id} · ${trace.name||trace.label}`,unit:trace.unit||"mV",runId:id,timeMs,values});}const difference=alignedDifference(sources[0],sources[1]);await chart.restoreState([{mode:"time",signals:sources},{mode:"time",signals:[{...difference,id:`difference:${ids.join(":")}:${key}:${channel}`,label:`B − A · ${key}`,runId:null,description:`Exact timestamp difference from ${ids[1]} minus ${ids[0]}; no interpolation.`}]}]);$(".instrument-status").textContent=`A, B and B − A: ${difference.matchedSamples} shared timestamps; ${difference.unmatchedA}/${difference.unmatchedB} unmatched samples omitted. No interpolation.`;}catch(error){onStatus?.(error.message);$(".instrument-status").textContent=error.message;}});
  refresh();return{refresh,setTime:ms=>chart.setTime(ms),exportState:()=>chart.exportState(),restoreState:s=>chart.restoreState(s),dispose(){disposed=true;chart.dispose();summaries.clear();}};
}
